### ISSUE TITLE
Guest user cloud sync

### ISSUE THREAD

**Issue by dyang** [aws-amplify/amplify-ios#1023]
**Is your feature request related to a problem? Please describe.**

I'm working on a mobile app where I'd like to give new users guest access without requiring them to register first. This works fine until the app gets updated and there's a schema update. When this happens, Amplify will wipe out local data, and without having user's data sync'd first, users will have to start all over again. 

To me, losing user's data is a showstopper. I might have to ask users to register before they can use the app.

**Describe the solution you'd like**

I wonder if it's possible to do cloud sync even if user is a guest? This behaviour can be disabled by default. 

**Describe alternatives you've considered**

Another solution would be to do client-side data migration, instead of wipe everything out when there's a schema change. This still doesn't save guest user's data if the app is deleted, but that's also expected. 

**Additional context**

I've enabled the following categories according to the developer guide:

- API
- DataStore
- Authentication (cognito, guest access enabled)
- S3Storage

**Comment by ruiguoamz** [comment]
Hi, @dyang 
Thanks for reaching out

1. I wonder how your schema is like. Is your schema with [`@auth`](https://docs.amplify.aws/cli/graphql-transformer/auth#auth) directive enabled? Because you have mentioned both `guest user data store` and `signed-in user data store`. If yes, then unfortunately, multi-auth is not supported so far, you can't sync data with a guest user if you use @auth schema. But from your description, you says your schema works fine with guest user, then I guess you do not have @auth enabled. 

2. Database clean up when there is a schema change is the expected behavior.

3. About the data migration feature, I am not sure if we are going to support or not or it is possible and feasible to do that. Because we do not have the ability to predict how user is going to change their schema. When there is a schema change, user needs to do `amplify codegen models` to generate the new `AmplifyModels` so that `API` and `DataStore` works normally. We can't do Amplify-related operation based on the old schema and database.

Hope you can elaborate on bullet 1 I posted and your thought on every bullets. Thanks

**Comment by dyang** [comment]
Hi @ruiguoamz, thanks for the information! 

Regarding 1, yes I do have `@auth` enabled on several of my models, as I want to limit data access to their owners. 

If guest user's data can't be sync'd with `@auth` schema, do you know if this is something that might be supported in the future? Do you know of any workaround to do something similar with the current version? Thanks!

**Comment by ruiguoamz** [comment]
Hi, [multiple @auth directive](https://docs.amplify.aws/cli/graphql-transformer/auth#combining-multiple-authorization-types) is in our plan. (sorry for the confusion, although we have it documented, but we actually doesn't support it right now)

I honestly do not have a good workaround so far. But I wonder if you can have a separate and identical schema but without @auth directive. I haven't try this before.

**Comment by dyang** [comment]
Hi, it's good to know that supporting multiple auth is in the plan. Do you know if it's something that'll come this year? 

I thought about having another schema without `@auth` but didn't proceed with it. I'm a bit concerned that it might lead to other issues if deviate too much from the standard.

**Comment by ruiguoamz** [comment]
Honestly, I am neither sure on the exact feature behavior nor the feature release date.

**Comment by lawmicha** [comment]
> Hi, it's good to know that supporting multiple auth is in the plan. Does it make it possible for guest users to sync data? 

I believe once this is supoprted, you will be able to use a schema that contains models annotated with `@auth` directive containing `allow: public`. allow public means any users (guest or authenticated) can persist their data normally with the local store through `DataStore.save()` on that model and they will be synced to the cloud using the APIKey as the auth mode on that endpoint. Once you perform a non-breaking schema update, the local store can be cleared and a full sync can be performed when the app is launched to get the data from the cloud.

**Comment by dyang** [comment]
@lawmicha - Thank you for the information! I'm looking forward to the feature. :-)

**Comment by silasmahler** [comment]
> > Hi, it's good to know that supporting multiple auth is in the plan. Does it make it possible for guest users to sync data?
> 
> I believe once this is supoprted, you will be able to use a schema that contains models annotated with `@auth` directive containing `allow: public`. allow public means any users (guest or authenticated) can persist their data normally with the local store through `DataStore.save()` on that model and they will be synced to the cloud using the APIKey as the auth mode on that endpoint. Once you perform a non-breaking schema update, the local store can be cleared and a full sync can be performed when the app is launched to get the data from the cloud.

Hello, can you elaborate on the non-breaking schema-update? In which cases the schema breakes.
