### ISSUE TITLE
Error when running Cognito auth app created from tutorial

### ISSUE THREAD

**Issue by Fuerteventura2022** [aws-amplify/amplify-ios#1074]
**Describe the bug**
When clicking 'Sign In' on an app I created from the AWS tutorial at the following location: https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-three/

On the third step, I complete as per the tutorial and launch my app. The sign in button appears as expected. When I click on it, I get an error which states the following:

**Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value**
The line of code it is marked against is as follows:
`let hostURL = "https://\(webDomain!)"`

Webdomain appears to be a variable that is assigned a value (or not in this case) as follows:
`let webDomain = infoDictionary?["WebDomain"] as? String`

The code seems to be in the file AWSMobileClient.swift.

**To Reproduce**
Create the app using Xcode 12.4 in the tutorial here:
https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/

When creating the app, select IOS, APP (Single view app is not available), Interface:SwiftUI, LifeCycle: UIKit App Delegate, Language Swift.

**Expected behavior**
A login interface to appear
**Screenshots**

![Image 21-02-2021 at 19 19](https://user-images.githubusercontent.com/79410446/108635905-e5312480-7479-11eb-8276-ae069e937f94.jpeg)

**Comment by ruiguoamz** [comment]
Hi, @Fuerteventura2022 

Thanks for reaching out. 

**There are few things I wonder:**
1. I wonder why single view app selection is not available.
2. Can you check if the `amplifyconfiguration.json` has the necessary information to configure `Amplify`? I assume you are using `signInWithWebUI` since you were following the tutorial. The json file should look like this:
```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-west-2:****",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-west-2_****",
                        "AppClientId": "****",
                        "AppClientSecret": "****",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "****.auth.us-west-2.amazoncognito.com",
                            "AppClientId": "****",
                            "AppClientSecret": "****",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

**My suggestion**
The tutorial you followed is a bit out-dated and there are few steps not accurate. You can follow this [doc](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios) which we keep it up-to-date regularly. Feel free to reach out if it doesn't work

**Comment by Fuerteventura2022** [comment]
@ruiguoamz thank you so much for your help. I've got it to say **YourApp wants to use Amazon Cognito to sign in** and then it says page couldn't be found. I'm pretty sure that's because I don't know the correct details for the following:

`"Auth": {
                            "WebDomain": "****.auth.us-west-2.amazoncognito.com",
                            "AppClientId": "****",
                            "AppClientSecret": "****",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },`

  I added that into **amplifyconfiguration.json** manually - it wasn't;'t self generated when the json files were created. Are you able to direct me to where I can find the missing info for:
WebDomain
AppClientSecret
SignInRedirectURI
SignOutRedirectURI

I'm guessing it's within AWS somewhere in Amplify? Many thanks again for your help.

**Comment by palpatim** [comment]
As part of a different issue, @sebsto is looking at the tutorial content to see if we can clarify this flow--some of the instructions are outdated. It may be that after we clarify the flow, you'll note a discrepancy between the correction and the flow you followed. In the meantime, you can take a look at our [Social sign in documentation](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios) for more up-to-date information on how to provision your Amplify backend and configure your client.

Leaving this open pending response from @sebsto.

**Comment by sebsto** [comment]
This error usually happens when there is no callback entered during Cognito configuration.
This are lines 7 and 9 in the section "[Create an authentication backend](https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-three/)".
and step d. "Trigger Authentication at Runtime" on the same page

I will take action to make these two steps more clear in the tutorial.

**Comment by jvanakker** [comment]
When using Amplify Studio to configure authentication (instead of using the CLI like the the mentioned tutorial), I get the same error as the original poster.

So when using
`Amplify.Auth.signInWithWebUI`

I get:
`WSMobileClient/AWSMobileClient.swift:508: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

But when using the new Amplify Studio, I shouldn't need to do "amplify add auth" and "amplify push", correct? Since everything is configured in Amplify Studio.
