### ISSUE TITLE
Using Amplify within an XCFramework

### ISSUE THREAD

**Issue by sha8wn** [aws-amplify/amplify-ios#1077]
Hello AWS Team,

**Is your feature request related to a problem? Please describe.**
- I am currently developing an XCode Framework for iOS which will be integrated into other apps via CocoaPods
- Amplify is one of my Frameworks dependancies and it will be downloaded along with my own framework
- When I try to initialize with try Amplify.configure(), it always fails because it seems it cannot find amplifyconfiguration.json
- The reason is when Amplify searches Bundle.main, amplifyconfiguration.json does not exist in the client application but it is within my frameworks bundle

**Describe the solution you'd like**
- Is there a way to manually integrate Amplify and Cognito without CocoaPods ?
- Better yet, could we specify to Amplify which bundle to search within ?
- Or could AmplifyConfiguration(bundle: ) be public so that I could specify the bundle and create the configuration
- Any other ideas or workarounds ?

**Comment by palpatim** [comment]
Hi @sha8wn,

The [`Amplify.configure(_:)` method](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Core/Configuration/AmplifyConfiguration.swift#L91) allows you to specify an in-memory configuration object, which you can either create manually in-memory, or [construct from a file URL](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Core/Configuration/AmplifyConfiguration.swift#L66).

Hope this helps.

**Comment by sha8wn** [comment]
Thanks @palpatim - definitely helps and worked ! I have another quick question, not sure if I should make another question so do let me know.

At the moment my backend team has provided me with a Pool Id and a region which I used in the config file and now I see a success after your advice above.

Now I have also been given a bunch of functions / lambda's to invoke along with their payloads which I believe are inside the Cognito environment in AWS (I am not a backend guy) so am I using the right library to do this or should I use [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios) as I notice it has a [Lambda Invoker](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSLambda/AWSLambdaInvoker.h)

Thanks again in advance for your support.

**Comment by palpatim** [comment]
@sha8wn Glad that helped!

Regarding your next question: you've got a few options, and which one works best depends on the requirements of your use case.

1. You could front the Lambda with API Gateway, and use the Amplify API category to invoke it as a REST endpoint.
2. Depending on the auth requirements, you could potentially invoke the Lambda directly using the Amplify API category.
2. If the Lambda functions are ["Lambda triggers" that customize with user pool operations](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html), you wouldn't have to make any client-side calls at all; the triggers are invoked by Cognito during the appropriate operation request/response lifecycles.
3. You can use the Lambda SDK, which would allow you to directly invoke functions via a SigV4 signed request using appropriate Cognito role-based credentials.

Again, much depends on your use case, and the authorization requirements of your API. Feel free to open a new issue with more details and we can continue the conversation, but for now, I'll close this issue since the original question seems to be resolved.
