### ISSUE TITLE
DynamoDB tables seemingly inaccessible via Amplify?

### ISSUE THREAD

**Issue by end3r117** [aws-amplify/amplify-ios#1079]
**Is your feature request related to a problem? Please describe.**
In the CLI, I am able to "amplify add storage" that creates a DynamoDB table, yet I cannot seem to find a `pod` / plugin for writing to / reading from that DynamoDB table, one which I could presumably add to `Amplify.add(...)` inside `AppDelegate`, prior to calling `Amplify.configure()`.

**Describe the solution you'd like**
A DynamoDB plugin / escape hatch.

**Describe alternatives you've considered**
None, as I read the AWS iOS SDK will--as a move to force adoption of Amplify--be deprecated in October? Or just no longer supported...? In any case, upon actually using Amplify, I think it definitely makes quickly prototyping a backend easier but of course is still experiencing some growing pains =P

**Additional context**
All tutorials point to using S3 for "Storage", so why is there even a DynamoDB option? I just want to update a table, manually--I don't need AppSync (for this project anyway.. shout out AppSync, I love it normally) / DataStore.

Amplify config is as follows:

Auth:

- SIWA (works fine)

Storage:

- S3 storage (works great)

- NoSQL storage (reason for writing this)

I should note that the `amplifyconfiguration.json` file has the following (obfuscated) entries for "Storage":

```
"storage": {
    "plugins": {
        "awsS3StoragePlugin": {
            "bucket": "bucket",
            "region": "region",
            "defaultAccessLevel": "level"
        },
        "awsDynamoDbStoragePlugin": {
            "partitionKeyName": "partitionKeyName",
            "region": "region",
            "arn": "arn:aws:dynamodb:region:table/tablename",
            "streamArn": "arn:aws:dynamodb:region:table/tablename/stream/timestamp",
            "partitionKeyType": "S",
            "name": "tablename"
        }
    }
}
```

**Comment by lawmicha** [comment]
Hi @end3r117, thanks for bringing this up, i'll first mark it as duplicate of https://github.com/aws-amplify/amplify-ios/issues/636 and at the moment that issue is marked as wont fix so there are no any plans for supporting a DynamoDB plugin for the storage category.

There is an improvement that can be made so that the CLI experience does not let you choose a provisioning that currently does not have a library plugin that supports it. We prioitized to build the plugin for S3 for the storage category (`Amplify.Storage.upload / download` to S3) so there is no storage plugin for DynamoDB. 

If you would like to interface with DynamoDB, we recommend interfacing it through AppSync or APIGateway. You can `amplify add api` and choose GraphQL to provision the AppSync endpoint with the resolvers to DynamoDB, or REST to create an APIGateway to front your lambdas that write to DynamoDB.

The escape hatch option: If you still want to work directly against DynamoDB, you can use the SDK (https://github.com/aws-amplify/aws-sdk-ios/tree/main/AWSDynamoDB) and use Amplify to get your static credentials https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios

As mentioned, we will focus the "library" development in Amplify, however the SDK's that are auto-generated will continue to be maintained and updated (https://docs.amplify.aws/sdk/q/platform/ios).

I would like to understand your requirements better

- what does your DyamoDB tables look like? what data are you looking to store in DynamoDB?
- what are some high level use cases you are looking for perform against DynamoDB?
- How is the data in DynamoDB being used elsewhere?

**Comment by end3r117** [comment]
Hey @lawmicha, thanks for the clarity! Good to know that the iOS SDK will be maintained, for those of us who prefer the manual approach--although, again, I did appreciate the quick provisioning provided by Amplify.

### What do your DynamoDB tables look like? What data are you looking to store in DynamoDB?
As I mentioned, I'm using Sign In With Apple (SIWA) for auth, and since Apple only provide user info (email, full name) the very first time a user authenticates, regardless of device, I was simply attempting to store a user object in a Dynamo table for my client's app's future use.
### What are some high level use cases you are looking to perform against DynamoDB?
A better cross-device UX and the ability for user to change the email and other attributes associated with their Apple user identifier, should they want to do that. S3 is meant to store / retrieve large objects based on Apple's user identifier, so associating that user with attributes was my goal (although I don't actually know how persistent Apple's user identifier is... but so far it seems to remain the same across test devices, even if Cognito's identityID can potentially change).
### How is the data in DynamoDB being used elsewhere?
Matching Apple's user identifier with stored user attributes / S3 objects across devices.

Note: my client does not want to use a username / password auth workflow for the moment, so my hands are a little tied having to use only SIWA for auth.

**Comment by end3r117** [comment]
On second thought, AppSync (via Amplify api) with a simple User model will work just fine and be more convenient. Thanks again.
