### ISSUE TITLE
Datastore - Changing Schema Breaks Query

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-ios#1083]
**Describe the bug**

For Amplify iOS - Datastore, if a user saves a model instance, then modifies its modelSchema to add another field, then runs amplify codegen models, a crash happens:

```
Query API failed. Error = DataStoreError: The operation couldn't be completed. (SQLite.Result error 0.)
Recovery suggestion: The operation couldn't be completed. (SQLite.Result error 0.)
```

**To Reproduce**

1. Create the following schema: 

type Note @model {
  id: ID!
  content: String!
}

2. Save the model and then query.  Observe no error.

3. Update the schema: 

type Note @model {
  id: ID!
  content: String!
  name: String
}

4. Run query.  Don't save. Observe the error: 

```
Query API failed. Error = DataStoreError: The operation couldn't be completed. (SQLite.Result error 0.)
Recovery suggestion: The operation couldn't be completed. (SQLite.Result error 0.)
```

**Expected behavior**
No error after changing the modelschema and running query

**Screenshots**
Here is the local DB on the phone.  As you can see it's updated to include the extra fields: 
![image](https://user-images.githubusercontent.com/11478656/109581748-b5a19e00-7ab1-11eb-94a3-6ec40eb99358.png)

Also on the AWS Amplify console you can see the extra fields as well: 
![image](https://user-images.githubusercontent.com/11478656/109581781-cb16c800-7ab1-11eb-971d-921bd2950017.png)

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 14.2

**Comment by palpatim** [comment]
@fjnoyp Thanks for reporting this.

Right now we don't have a mechanism for supporting [local migrations](https://docs.amplify.aws/lib/datastore/schema-updates/q/platform/ios), but I wouldn't expect a crash--the documented behavior is that we remove local items and re-sync from the cloud.

**Comment by ruiguoamz** [comment]
Hi, @fjnoyp 

Are you talking about the usage with sync enabled or disabled?
For whichever use case, I don't see a crash. But I do see subscription fails to be established for one case which I explain below

No matter for sync enabled or not, as long as there is a schema change, the local database will be cleared as @palpatim mentioned: we don't support for local data migration and we don't have control over customer's change of schema. 

In this case the difference is the sync part:

If sync is enabled, when you change your schema, you should do a `amplify push` and then `amplify codegen models`, in this case, no error will be returned and thus no crash with the schema you provided. The sync will still be kicked off and when you do a query, the following result should be returned:
```
Note(id: "uuid********whatever", content: "note7", name: nil)
```

but if you skip doing `amplify push`, it fails to set up subscription, and since local database is cleared, you will get an empty array.

Maybe please provide more detailed reproduction steps that we can help out. Thanks
