### ISSUE TITLE
Feedback Request: How would you improve Amplify Library for iOS?

### ISSUE THREAD

**Issue by hdworld11** [aws-amplify/amplify-ios#1084]
Please comment on this issue to let us know how you would improve Amplify Library for iOS.

We are looking forward to hearing from you so we can better address your needs!

**Comment by anatomybook** [comment]
First of all, I'd like to point out that the library is great. It generally works well for me and I'm happy to see it get better.

Two things come to mind, regarding improvement:
1. **Error handling**. If somewhere deep inside the library an error occurs, I'd like to know about it. For example, currently some SQL Lite errors are not propagated. Or perhaps I should generalise that to robustness. When really torturing the lib, i.e. doing disconnects during sync, changing local state offline, then going online again, killing sync in middle and so on, I was able to produce inconsistent data - without error message. Again, I'm 100% positive that this is normal during early stage of development. But I'd look into that direction.
2. **Speed**. This is a vague one, since I haven't done any timing. But I seem to recall, that I saw higher performance when syncing many items using Apollo. I may be wrong here.

In general I think I'd put new features on hold and stabilise what's there so far. A quick grep for TODO reveals many hits.

I hope this makes sense. Let me know, if you have any questions.
