### ISSUE TITLE
Cognito with Google Sign-in birthdate error.

### ISSUE THREAD

**Issue by RadoslawCzubak** [aws-amplify/amplify-ios#1088]
**Describe the bug**
I have set Cognito with federated login - Google Sign-in. The problem is that I get this error
`Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: Invalid user attributes: birthdate: String must be no longer than 10 characters
 }`
As a user's attributes are set birthday, gender, email, username and name. It seems to be configured well, but Google sign-in passes wrong date format.

**To Reproduce**
Setting up according to documentation.
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios#setup-your-auth-provider

**Expected behavior**
Cognito gets proper birthdate and users can log in.

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Dependency Manager: Cocoapods
 - Swift Version: 5
 - CLI Version: 4.44.1

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 14.4

**Comment by palpatim** [comment]
@RadoslawCzubak Thanks for reporting this. To confirm, you're setting up your authentication to use the WebUI, which means that the error is in the data passed directly from Google to the Amazon Cognito service. Unfortunately, the Amplify library won't be able to work around that since those are service-side data flows.

This appears to be a [known issue](https://forums.aws.amazon.com/thread.jspa?messageID=826333). I'd recommend adding a +1 to that Forums issue and separately I'll re-raise it with the Cognito team to bring it to their attention. They may be able to suggest a workaround that can help.
