### ISSUE TITLE
amplify codegen compilation errors

### ISSUE THREAD

**Issue by htc007** [aws-amplify/amplify-ios#1089]
**Describe the bug**
amplify codegen generates API.swift with the following compilation errors:

**Screenshots**
![Ambiguous use of operator '+-'](https://user-images.githubusercontent.com/79252165/110088386-c57df280-7dcf-11eb-8ed1-131b33f7b72b.png)

![type String and optional value contains 'nil'](https://user-images.githubusercontent.com/79252165/110088398-c878e300-7dcf-11eb-8b1c-1c80403e19ca.png)

In order to use it, we have to manually fix these errors.

**Environment:**
 - Amplify Framework Version: 1.5.2
 - Dependency Manager: Cocoapods 1.10.1
 - Swift Version: 5.3.2
 - CLI Version: 4.44.1

**Comment by palpatim** [comment]
@htc007 

The **API.swift** file is intended for use by the [AWSAppSync SDK](https://github.com/awslabs/aws-mobile-appsync-sdk-ios). The model files you want are in the **<PROJECT_ROOT>/amplify/generated/models** subdirectory.

Sorry for the confusion on this--because we still support the older AWSAppSync SDK, it's easy to generate the **API.swift** file during normal CLI operations, but feel free to remove the file if you see it, and don't add it to your Amplify-based app if you do see it.

**Comment by palpatim** [comment]
@htc007 The DataStore and API category are built on top of the AWS AppSync **service**, but they do not use any part of the AppSync **SDK**. (The **API.swift** file that is generated for the AWS AppSync SDK conforms to the Apollo client's structure, while the generated model files for Amplify DataStore are model-based, as you have noted.) There is a common transport layer (AppSyncRealTimeClient) that both Amplify and the AWSAppSync SDK share, but there is no direct dependency on the two, and no plans to support the Apollo-style generated code in DataStore.

We are working to improve DataStore's ability to handle custom types and additional search capabilities such as the GSI case you called out, but can you explain the use case you're trying to solve having Data returned as JSON in DataStore? If you're writing to some other persistence layer, DataStore probably isn't the right solution for you, since its entire purpose is local access to app data, and as such has a tightly coupled persistence layer built in.

**Comment by htc007** [comment]
@palpatim We'd love to use DataStore and sync data using the auto-generated models, but we've struggled with too many limitations (e.g. https://github.com/aws-amplify/amplify-js/discussions/7771). We just have to move on, otherwise our fledling startup is going to fail out of the gate.

If we were to stick with DataStore, then obviously we don't need data returned as JSON. However, if we don't use DataStore yet still want to use the API category to get data and save it in some other mobile database (e.g. Realm), then the auto-generated models are troublesome since we have to encode it to JSON before we can save the data as Realm objects. We actually tried this, but soon found out that the auto-generated models don't work for a lot of the queries we have to make.

This ultimately led us to the AppSync SDK, which works fine, other than the issue with compilation errors in the API.swift file. We manually fix these errors at the moment, but your comments are starting to worry me as it seems like this is not a long term solution.

Do you have any suggestions for us? I would assume there are many mobile developers who wish to get data using the API category (failing which, the AppSync SDK) and store it in their own SQLite database on iOS and Android. How would they go about doing this without needing to encode the model to JSON?
