### ISSUE TITLE
Amplify.Auth.signInWithWebUI works but Amplify.Auth.signIn gives error on iOS

### ISSUE THREAD

**Issue by DNCoding** [aws-amplify/amplify-ios#1129]
**Describe the bug**
When I tried to login using Amplify.Auth.signInWithWebUI, the login is success.  But when I have used Amplify.Auth.signIn it throws the following error.

signIn(username:password:): Sign in failed - AuthError: Unexpected error occurred with message: nil: Error information not available.
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/xxxxx/Development/Projects/Demo/AmplifyDemo/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79 

public func signIn(username: String, password: String) {
        Amplify.Auth.signIn(username: username, password: password) { result in
            switch result {
            case .success(let signInResult):
                if case .done = signInResult.nextStep {
                    print("\(#function): Sign in succeeded")
                }
                else {
                    self.processSignInNextStep(username: username, nextStep: signInResult.nextStep)
                }
            case .failure(let error):
                print("\(#function): Sign in failed - \(error)")
            }
        }
    }

public func signInWithWebUI() {
        Amplify.Auth.signInWithWebUI(presentationAnchor: UIApplication.shared.windows.first!) { result in
            switch result {
            case .success(let signInResult):
                if case .done = signInResult.nextStep {
                    print("\(#function): Sign in succeeded")
                }
                else {
                    self.processSignInNextStep(username: username, nextStep: signInResult.nextStep)
                }
            case .failure(let error):
                print("\(#function): Sign in failed - \(error)")
            }
        }
    }

amplifyconfiguration.json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-central-1_vhj2vn9yj",
                        "AppClientId": "*****************",
                        "Region": "eu-central-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "*****.eu-central-1.amazoncognito.com",
                            "AppClientId": "****************",
                            "SignInRedirectURI": "awsdemo://",
                            "SignOutRedirectURI": "awsdemo://",
                            "Scopes": [
                                "openid"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}

**Environment(please complete the following information):**
 - Swift Version:  5.4
 - CLI Version: 4.46.1
 

**Device Information (please complete the following information):**
 - Device:  iPhone11, Simulator
 - iOS Version:  iOS 14

**Comment by ruiguoamz** [comment]
Hi, @DNCoding 
Thanks for reaching out. 

Could you provide more info? 
1. what steps to follow to reproduce the issue? 
2. Which Amplify version are you using? 
3. Why the `signInURI` you provided is "awsdemo://"?

**Comment by stefanoandreetta** [comment]
I'm having a very similar issue, only on one iPhone (XS), but not on an older iPhone 6 and also not on the simulator.

I think it could be related to the permission request to open amplify to login (The classic message prompted to the user "AppName would like to use Amplify to do something"). In the iPhone XS this message won't be shown also after reinstalling and rebooting the phone.

SignInWithWebUI goes to the "failure" case and the error is "unknown" type.

This is the message it gives to me:

`An unknown error occurred  -  Optional(Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant})
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/Stefano/Documents/workspace/iOS/XeniApp-iOS/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}
An unknown error occurred  -  Optional(Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant})
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/Stefano/Documents/workspace/iOS/XeniApp-iOS/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}
An unknown error occurred  -  Optional(Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant})
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/Stefano/Documents/workspace/iOS/XeniApp-iOS/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}`

**Comment by stefanoandreetta** [comment]
I can confirm it is related to the permission request, as I deleted my app, waited for a day and then reinstalled it and after that, the "app would like to use amazoncognito.com to access ..." appeared again.

**Comment by lpbreen** [comment]
@DNCoding have you made any progress in fixing this issue? I'm encountering the exact same problem as you - my code and amplifyconfiguration.json are structured the same as yours.

It's interesting because on some level the authentication seems to be working... when I submit the wrong username/password I get back a "wrong username/password" error, but when they're correct I receive the "Unexpected error occurred with message: nil: Error information not available." Based on this I'm thinking there must be an issue in our amplifyconfiguration.json but can't say for sure

**Comment by DNCoding** [comment]
Hi All,

Sorry for replying late. I keep changing the settings in userpool and it started working and was not knowing which change made it to work. So, I re-did everything and found that when MFA for TOTP is enabled, the login failed with signIn, when it is set to OFF or optional both sign in is working.

Thanks for your informations and support.

Regards
