### ISSUE TITLE
Deletions are not performed safely

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1157]
**Describe the bug**
Consider an object hierarchy, such as the one given in the documentation (Post / Comment). If one deletes the Post, the lib will also take down all the associated comments. However, if the delete is interrupted by, say, the user locking the device, the database is left in an inconsistent state, i.e. Comments without Post are around. If a second device syncs on this state, many errors will occur. Most notably, the `HubPayload.EventName.DataStore.ready` never gets triggered as well as the sync seems to restart itself multiple times.
If the first device commences, it'll clean up the remaining items. However, one cannot count on this, as the user may also choose to "clean" the task list and kill the app completely, leaving the backend in an inconsistent state.

**To Reproduce**
1. Create a hierarchical data model with dependencies.
2. Create exemplary data where a root item contains many children, such that the deletion of the children will take some time.
3. Delete the root item and immediately afterwards lock the device, such that the deletion of the children is interrupted.
4. Verify in the backend, that the root item is gone and at least some children are still around
5. Sync a second device from scratch and observe the sync process having trouble

**Expected behavior**
I expect the backend to **always** be in a consistent state, regardless of what the devices do. Deletions of items with dependencies that would be become orphans need to be atomic. Or at least the children need to go first, such that the database may still be synced, even of the result would be questionable contentwise. But from a technical point of view, it'd be fine.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.7.2
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0

**Device Information (please complete the following information):**
 - Device: Simulators will do to reproduce
 - iOS Version: iOS 14
 - Specific to simulators:

**Additional context**
I briefly touched upon this issue [here](https://github.com/aws-amplify/amplify-ios/discussions/1097#discussioncomment-471914) already.

**Comment by anatomybook** [comment]
Hello @lawmicha ,

I'm sorry to bother you, but I was wondering if there's any update on this. I'm coming increasingly often across this issue. Each time I'll end up cleaning the database manually.

Thank you!

**Comment by lawmicha** [comment]
Hi @anatomybook,

>  Deletions of items with dependencies that would be become orphans need to be atomic.

I believe the cascade delete feature that DataStore is currently implemented is best-effort and does not do this atomically, and so that's why this is an issue that you described, data is simply not being deleted while the local SQLLite enforces the parent to exist when syncing a child object. 

I believe the bug here that needs to be fixed is even in this state: there are orphaned children in the remore store.. in the second device, it will attempt to sync all of them to the local store resulting in foreign key constriant issue. The sync engine should handle them gracefully and eventually emit the ready event.

**Comment by anatomybook** [comment]
Hallo @lawmicha ,

thanks for looking into this!

Yes, it would help very much if the sync engine could handle this gracefully. I suggest that it should attempt to delete the item in the backend, if the parent is missing as it is lost for "regular" usage. This would also keep the database clean.

If the ready event was 100% reliable, I could remove some workarounds in my code. That would tremendously help me and likely many others as well.

Anyhow, please let me know if there's anything I can do to help.

**Comment by lawmicha** [comment]
Hi @anatomybook I'm working on a PR https://github.com/aws-amplify/amplify-ios/pull/1321 that should stabilize things. 

Will think about your suggestion some more. We should also focus on cascade delete's functional consistency. If an item fails to delete from the backend, it should keep the mutation event and try again later. I think it's already doing this but eventually treating the error as processed and removing it from the queue, such that the remote store's parent object doesn't end up getting deleted. There are other scenarios which may lead to the error, for example the default max items to sync is set to 10k items so if a parent object doesn't get saved because it was never retrieved, the child object will be orphaned as well.

**Comment by anatomybook** [comment]
Hi @lawmicha ,

thanks for your response and for looking into this. I can't wait for the fix as this will help my app tremendously. 

Let me know if you want me to test it out.

**Comment by anatomybook** [comment]
Thank you for looking into this. I can confirm that it works with d4de998182fa99fea0900acf5bc6ebf7a0bc691f. At least the syncing does. I did not check the backend. But as long as the clients sync cleanly, I'm happy.
