### ISSUE TITLE
ITMS-90863: Apple silicon Macs support issue 

### ISSUE THREAD

**Issue by Parag2385** [aws-amplify/amplify-ios#1172]
Hello,

As the title mentions got this email from App Store Connect for the frameworks whenever deploying the app to TestFlight.

Also, the app keeps crashing when trying to open when downloaded from TestFlight. Everything works perfectly fine when the app is installed on Simulator directly from Xcode.

We're using Carthage to manage the dependencies. If that's relevant.

Please check the following screenshot for the email we got.

![image](https://user-images.githubusercontent.com/10680096/115283454-ff7d3b00-a168-11eb-89be-077c79edd74f.png)

Please let me know, how can I resolve this.

Thank you.

**Comment by palpatim** [comment]
The AWS SDK for iOS does not support Mac--can you verify that your app's destinations are limited to only iOS? Also, I see you're filing this issue in Amplify repo, but Amplify does not support installation via Carthage. Can you:

- Clarify whether you're using the Amplify Library for iOS, or the AWS Mobile SDK for iOS, so we can track this in the appropriate repo?
- Provide the details we request in our [bug report](https://github.com/aws-amplify/amplify-ios/issues/new?assignees=&labels=&template=bug_report.md&title=)? I've pasted them below for your convenience.

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here.
