### ISSUE TITLE
 "Make sure that the request made to the particular AWS resources.." error when sign up with email and password

### ISSUE THREAD

**Issue by hellopandaxx** [aws-amplify/amplify-ios#1174]
Hello guys,

we use amplify for signing up our users and one of them reported some strange issue during sign up with email and password: "Make sure that the request made to the particular AWS resources.."

Can you please advise me what can be the issue?

**Comment by palpatim** [comment]
Can you please provide more detail, including at a minimum some consistent repro steps? I've pasted the bug report template below for your convenience.

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here.
