### ISSUE TITLE
Apple sign in loses context of private session after reinstall but still has valid credentials in keychain

### ISSUE THREAD

**Issue by mattcat10** [aws-amplify/amplify-ios#1185]
**Describe the bug**
Currently we have a need to clear all authentications on a fresh install ([as suggested here](https://docs.amplify.aws/lib/info/app-uninstall/q/platform/ios)). If a user signs in with apple with the web ui with `.preferPrivateSession()` option set, then uninstalls our app, reinstalls, then call Amplify.signOut on app launch we lose context of the privateSession and the app prompts the user with the "..... Wants to Use ..... to Sign In" prompt. This scenario happens when a user still has a valid credential stored in their keychain after reinstalling. This is a really bad experience for the user.

**To Reproduce**
1. Sign in with apple ```Amplify.Auth.signInWithWebUI(for: provider, presentationAnchor: anchor, options: .preferPrivateSession())```
2. Remove app off phone without signing out
3. Reinstall app calling ```Amplify.Auth.signOut()``` on first launch
4. See prompt asking user to sign in

**Expected behavior**
Expected behavior would be that sign out occurs without prompting user with a web UI or "sign in prompt". 

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.7.2
 - Dependency Manager: Cocoapods
 - Swift Version: 5
 - CLI Version: N/A

**Device Information (please complete the following information):**
 - Device: Tested on iPhone 11 & simulator
 - iOS Version: 14.4.2
 - Specific to simulators:

**Comment by jgale** [comment]
We are experiencing this exact bug too, and worried it might hold us back from launching a Cognito-based solution. Have you discovered any workarounds @mattcat10?

**Comment by jgale** [comment]
Following up, we came up with a workaround. When the app starts up and it's a fresh install, we clear the Keychain-related items via: 

```
let spec: NSDictionary = [kSecClass: kSecClassGenericPassword]
SecItemDelete(spec)
```

That seems to clear the bad state, and then the user can sign in again. Note that this is a pretty blunt instrument. If you have other generic password items stored in your app's keychain, this will blow them away too.

**Comment by mattcat10** [comment]
@jgale we have not done any work around at this point, i'll have to try your workaround.

**Comment by palpatim** [comment]
This is working as _designed_, as noted [here](https://docs.amplify.aws/lib/info/app-uninstall/q/platform/ios). However, it's not necessarily working as _expected_, since credential information persisting across app installs can certainly be surprising.

I've opened https://github.com/aws-amplify/amplify-ios/issues/1314 to track a feature request to handle this in the Amplify Library, and am closing this issue since the workaround described is our current best practice.

**Comment by jgale** [comment]
I would argue that it's unexpected that `.preferPrivateSession()` will cause the alert at all. My whole goal in using it was to *avoid* that alert. I also find it very unexpected that the pop-up ever gets triggered during a `signOut` operation, since I assumed it was just a vanilla network API call and had no need for `ASWebAuthenticationSession`. The fact that it persists across app installs just makes it even more surprising.
