### ISSUE TITLE
Ignore federated identities in custom auth flow.

### ISSUE THREAD

**Issue by michalgorka** [aws-amplify/amplify-ios#1202]
Hi. In my app I'm using custom auth flow without federated identities and custom users db. After login i can not get accessToken because auth module required  federated identities configuration. Can you add extra param into configuration json to ignore FI?

**Comment by royjit** [comment]
Hi @michalgorka can you provide a few more information so that we can help to debug the issue?

- Steps to reproduce the issue
- aws configuration used
- Auth api used to sign in
- Error message or logs (please remove any sensitive information before posting here)
- Screen shots if applicable

**Environment info:**
 - Amplify Framework Version: [e.g. 1.5.3]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`
