### ISSUE TITLE
Cannot launch Cognito Hosted UI after session expiration.  

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-ios#1204]
**Describe the bug**
After signing in via Hosted UI by calling `Amplify.Auth.signInWithWebUI` and then allowing the Cognito User Pool refresh token to expire, calls to `Amplify.Auth.fetchAuthSession` return exceptions stating that the session is expired and instructing the user to sign in again. However, subsequent calls to `Amplify.Auth.signInWithWebUI` result in the following:

```
AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/dnnoyes/Projects/amplify-flutter/packages/amplify_auth_cognito/example/ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}
  ▿ unknown : 2 elements
    - .0 : "An unknown error occurred"
    ▿ .1 : Optional<Error>
      - some : Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}
```     

**To Reproduce**

1. Call `Amplify.Auth.signInWithWebUI` and log in via Google. Login is successful.
2. Allow refreshToken to expire (60 minutes).
3. Call  Amplify.Auth.fetchAuthSession, which return expired session tokens (as expected).
4. Attempt Amplify.Auth.signInWithWebUI again.  The exception described above is thrown. 
5. In order to proceed, `signOut` must be called.

**Expected behavior**
Users should be able to re-signin without first signing out.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.9.0
 - Amplify Categories:
   - [ ] Analytics
   - [ ] API
   - [X] Auth
   - [ ] DataStore
   - [ ] Predictions
   - [ ] Storage
 - Dependency Manager:  Cocoapods
 - Swift Version: 5.0
 - CLI Version: Custom version
 - Xcode Version:  12.4 (12D4e)

**Is this a regression (i.e. was this working before a version upgrade?)
*If applicable provide the versions used before and after the upgrade.*

**Device Information (please complete the following information):**
 - Device: iPhone 12
 - iOS Version: iOS 11

**Additional context**
Via the debugger, I see that the code path is entering [this method ](https://github.com/aws-amplify/aws-sdk-ios/blob/d0ad8ac3516722a7271d8a2ae42da68e2de29478/AWSCognitoAuth/AWSCognitoAuth.m#L399)to check the session, and appears to possibly attempt to hit the refresh token endpoint. I am not entirely sure about this, but it seems odd that it would check this on a sign in attempt.

This was observed in an amplify-flutter project.

**Comment by royjit** [comment]
The signIn flow and getting session flow happens through the same code logic in AWSCognitoAuth SDK. Both of them will eventually call `getSessionInternal` method inside `AWSCognitoAuth.m`. 

The flow inside `getSessionInternal` is like follows:

1. Checks if there is a current user (this will be true for a signed in session and session expired case)
2. If the expiration date passed, it will use the refresh token to refresh the token 
3. Since the refresh token is also expired, it returns an error

Since signIn flow goes through the all the steps above, it always end up trying to refresh the token and then returning the error. Instead of this the signIn flow and getSession flow should be separated. The signIn flow should just bring up the hostedUI and let the user to signIn. 

I tried to handle this using the following PR - https://github.com/aws-amplify/aws-sdk-ios/pull/3565
