### ISSUE TITLE
Is it possible to use AppSync/GraphQL via Amplify libraries without the Amplify backend?

### ISSUE THREAD

**Issue by wedouglas** [aws-amplify/amplify-ios#1211]
So we're using Amplify libraries in our app (REST API, Cognito authentication etc), but we're not using an Amplify backend. So far so good. However, going through the documentation, there isn't much about using AppSync/GraphQL without the Amplify CLI backend setup.

We've got a schema, but it's not clear what else we can do with this without the Amplify backend. Seems like `amplify codegen models` is needed to generate additional files for the project, but there's no example of what's in these files or if these can be generated/configured and used without the Amplify backend.  

For REST API, it was simple enough to configure amplifyconfiguration.json and plug in the appropriate REST API endpoints, set up APIGs, etc. The iOS REST API functions were super easy to use and worked "out of the box", so to say. It's not so clear for AppSync/GraphQL...

Any suggestions or could anyone point me to some documentation on this? (I'd label this question, but didn't see a question label)

**Comment by palpatim** [comment]
If you already have an existing AppSync GraphQL backend, the "use existing resources" doc section is appropriate, but would rely on you to either craft custom response types or use raw GraphQL documents in your request. Similarly, you could deserialize the response of your GraphQL operation into a custom type, or String, Data, JSONObject, etc according to your need. You can see some examples in the [Advanced Workflows docs](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios).

What you don't get in the "existing resources" case is Amplify doing it for you--for the purposes of this discussion, that's the big benefit Models bring. Amplify uses AWS AppSync behind the scenes, but layers on additional metadata to support Models, with the primary use case being Amplify DataStore. Used with an Amplify-generated backend, the Amplify library behind the scenes converts your annotated models to GraphQL documents to pass to the AppSync endpoint, and deserializes the response into those same models. That work is supported by the code-generated Todo.swift, Todo+Schema.swift, and AmplifyModels.swift files you noted above. 

However, if you haven't set up the GraphQL endpoint with Amplify, adding models retroactively isn't supported, because that additional model metadata isn't available, and so Amplify can't generate Todo.swift, AmplifyModels.swift, etc. That metadata is only set up during the `amplify add|update api` workflows where we have direct access to the decorated model schema.

Hope this helps. If you want to pursue it further, please provide some details around the use case you're trying to support using models with an existing AppSync API.

**Comment by wedouglas** [comment]
Thanks for that, palpatim. For whatever reason, I totally missed the Advanced Workflows docs, which at first glance actually might be just what I'm looking for. I'll need to take a closer look at it.

I'll go ahead and close this since I think you sent me down the right path and answered my questions pretty well. If not, I'll be back!

Thanks again!
