### ISSUE TITLE
Verify SQLite limit to bind variables

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/amplify-ios#122]
Heaven forbid we ever hit it, but do I remember that SQLite has a limit on the number of bind variables on the order of 1,000? Might be worth verifying that and including it the documentation

_Originally posted by @palpatim in https://github.com/aws-amplify/amplify-ios/pull/116_

**Comment by palpatim** [comment]
Per [the SQLite Docs](https://www.sqlite.org/limits.html) (section "Maximum Number Of Host Parameters In A Single SQL Statement"), the default value is 999 prior to May 2020.

**Comment by palpatim** [comment]
But honestly, thinking about this, we probably don't want to even specify the limit, since that sort of implies that we've tested the system up to that point, and the SQLite limit is the thing that breaks us. If someone is using that many columns, there are almost certainly other problems that are going to cause failures, so I'm not inclined to worry about this limit. Closing wontfix.
