### ISSUE TITLE
An unknown error occurred during Amplify.Storage.uploadData() call

### ISSUE THREAD

**Issue by saravr** [aws-amplify/amplify-ios#1236]
**Describe the bug**
uploadData() failed with message "An unknown error occurred". Message indicated raising a bug report.

StorageError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /xxx.../Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79

**To Reproduce**
Upload image data by calling Amplify.Storage.uploadData().

**Expected behavior**

**Screenshots**

StorageError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /xxx.../Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Amplify Categories:
   - [ ] Analytics
   - [ ] API
   - [ X] Auth
   - [ ] DataStore
   - [ ] Predictions
   - [ X] Storage
 - Dependency Manager: [e.g. SwiftPM, Cocoapods] Cocoapods
 - Swift Version: [e.g. 5.0] 5.0
 - CLI Version: [e.g. 4.41.2, Run `amplify version`] 4.34.0
 - Xcode Version: [e.g. 12.4 (12D4e), Run `xcodebuild -version`]  12.4
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log` - No such directory

**Is this a regression (i.e. was this working before a version upgrade?)
No. Reused a working pattern from an earlier project. Replicated the AWS backend setup for the new project.

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**

**Comment by testflyjets** [comment]
I'm experiencing this exact same error. Also, since the error message included `Amplify/Categories/Auth/Error/AuthError.swift` in the error message, I decided to test to see if the Cognito Auth was actually returning the Identity ID that Storage needs. 

I followed this: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios

This code:

```
        // Get user sub or identity id
        if let identityProvider = session as? AuthCognitoIdentityProvider {
            let usersub = try identityProvider.getUserSub().get()
            let identityId = try identityProvider.getIdentityId().get()
            print("User sub - \(usersub) and identity id \(identityId)")
        }
```

is throwing the same AuthError when `try identityProvider.getUserSub().get()` is called. Not sure if this is helpful but thought I'd add it.

**Comment by testflyjets** [comment]
Digging into this further I did a `dump(session)` in the iOS code. This is part of what came back:

```
Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=10 "(null)" 
UserInfo={__type=ResourceNotFoundException, 
message=IdentityPool 'us-west-2:8xxxxxx-c4c6-4fb2-a89a-xxxxxxxxxxx' not found.}
```

I looked at the Cognito Identity Pool ID for the Amplify environment I was using and it was different. I updated the amplifyconfiguration.json and awsconfiguration.json files with the correct Identity Pool ID and things started working. I had previously updated the Cognito User Pool information in those files to match the Amplify env but didn't notice the Identity Pool ID was wrong.

It is not clear to me how the Cognito info got out of synch with the Amplify environment but I will see if I can cause the issue to come back again. It seems this is working as expected now.

**Comment by testflyjets** [comment]
To close out my comments, I changed the Cognito Identity Pool ID manually in amplifyconfiguration.json and then did an `amplify pull` to see if it restored the correct ID. 

It did, so my conclusion is that the branch of code I was in was pointing at a different Amplify environment and I failed to do a pull to get the correct Amplify environment configuration.

**Recommendation**
I would strongly recommend fixing the error message that @saravr posted, because in my case, it hid the exact and easily correctable issue that was causing the error, the incorrect Identity Pool ID.

**Comment by saravr** [comment]
Thanks for the detailed analysis. In my case, verifying Cognito pool id wasn't sufficient. I had to zap the entire Amplify config and start over and it worked. Possibly I may have overlooked one or two errors during amplify init/add and did not cleanup properly.
