### ISSUE TITLE
How do I add elements to the List<T> data type?

### ISSUE THREAD

**Issue by bumbleparrot** [aws-amplify/amplify-ios#1242]
**Is your feature request related to a problem? Please describe.**
This is not really a feature request but more of a question on using the models generated by amplify codegen.

**Describe the solution you'd like**
When you have a nested model that links to many, the data type generated is List < Model >. I have no idea now to add a new record to that List. 

I want to do this locally, AFTER adding to the list via GraphQL. This way the UI has the most recent update without needing a new fetch.

**Additional context**
Can you help me understand why you use List < T > versus a basic array [T]?
Maybe my usage pattern is incorrect?

**Use Case**

1. I look up an incident and grab its associated comments list. This is all done with a single GraphQL query.
2. I show the user the comments.
3. I let them add a brand new comment to the incident.
4. I immediately update the UI with the newly posted comment.
5. I let the user navigate away from the incident and immediately back (if the want to).
6. The cached version of the incident (with comments) does not have the new comments the user is expecting to be there.

**What's the best way to resolve this? Add the new comment data to the local copy? fetch the record again (somehow forcing no cache)?**

**Examples below truncated for brevity**
scheme example:

```
type Incident @model
@key(fields: ["id"])
{
  id: ID!
  comments: [Comment] @connection(keyName: "commentsByDate", name: "comment", fields: ["id"])
}

type Comment @model
@key(fields: ["id"])
@key(name:"commentsByDate", fields:["incidentId", "createdAt"], queryField: "commentsByDate" )
{
  id: ID!
  incidentId: ID!
  commentText: String
  incident: Incident @connection(name: "incident", fields:["incidentId"])
}
```

The amplify codegen models output is:
```swift
public struct Incident: Model {
  public let id: String
  public var comments: List<Comment>?
  
  public init(id: String = UUID().uuidString,
      comments: List<Comment>? = [],
  }
}
```

**Comment by diegocstn** [comment]
hi @bumbleparrot , one of the main reason behind the usage of a `List<Model>` over a plain array of models is to support lazy loading of large collections of objects.
You can access the underlying collection of `Comment` via the `elements` property of a `List<Model>`
```swift
var updatedComments = incident.comments?.elements ?? []
updatedComments.append(newComment)
```
and then create a new `Incident` object with a new set of comments, save it and optimistically update the UI.
```swift
let updatedIncident = Incident(id: currentIncident.id, comments: List(elements: updatedComments))
Amplify.DataStore.save(updatedIncident).sink {
        if case let .failure(error) = $0 {
            print("Error updating incident - \(error.localizedDescription)")
        }
    }
    receiveValue: {
        print("Incident and comment saved")
    }
```
DataStore will save the new incident first in the underlying local storage.

**Comment by bumbleparrot** [comment]
Hi @diegocstn , 

I tried this approach, but the elements attribute of the List is marked "internal" thus, it is not accessible outside of the class file.

Is there another way or am I just doing it wrong?

[https://imgur.com/a/egS3U4V](url)

**Comment by bumbleparrot** [comment]
A work around is to:
1. Iterate the list and create an array copy of the list.
2. Add the new record to the array.
3. Create a brand new list by setting the Elements attribute to the array.
4. Replace the reference to the original list to your brand new list!

this feels dirty but it works. @diegocstn , @palpatim , is this the only way?

**Comment by palpatim** [comment]
/cc @lawmicha 

We intentionally did not expose the ability to mutate the underlying elements of a List because of the internal state management Lists do to handle lazy loading across various data sources (DataStore, API). Mutating should be done through the List interface methods (such as happens by iterating on an "un loaded" List), not by directly accessing the underlying storage.

List conforms to `Collection`, which should allow you to do things like accessing via subscript or iterating over it, and of course you can access the `elements` readonly. 

If you want to mutate the UI state, you'll want to back it with a mutable collection like an array. If you're subsequently adding elements to your UI, you'd want to merge those elements into your backing collection according to whatever strategy makes sense. E.g., For simple use cases, you can have a backing array that you just `append(contentsOf: myList.elements)`. But more advanced cases may allow users to re-sort based on name, or date, or priority; but the List has a fixed order based on the originating query, which makes it unsuitable for this use.

We'd be happy to consider feature requests to handle UI use cases, but for now, consider List as a source to _populate_ your UI state's single source of truth, rather than the single source of truth in and of itself.

**Comment by lawmicha** [comment]
> I tried this approach, but the elements attribute of the List is marked "internal" thus, it is not accessible outside of the class file.

Hi @bumbleparrot, which version of Amplify are you using? Could you try upgrading to the latest? Currently 1.9.2 is released and `elements` has been made public: https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/DataStore/Model/Collection/List+Model.swift#L39

**Comment by palpatim** [comment]
> `elements` has been made public

public read only. :)

**Comment by bumbleparrot** [comment]
We can close this as the work-around is good enough for now.
