### ISSUE TITLE
How can I delete an item by id using GraphQL API WITHOUT local datastore?  No examples in documentation.

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1257]
I have an iOS amplify project that does not use Datastore.  I wish to delete an item and cannot see any examples in the documentation on how to do that.  What I have done is:
```swift
Amplify.API.query(request: .get(SomeObject.self, byId: someObject.Id)) { event in
    switch event {
    case .success(let result):
        switch result {
        case .success(let someObject):
            Amplify.API.mutate(request: .delete(someObject)) { event in
                // returns error: "DynamoDB:ConditionalCheckFailedException"
            }
        case .failure(let error):
            print("Got failed result with \(error.errorDescription)")
        }
    case .failure(let error):
        print("Got failed event with error \(error)")
    }
}
```
The error that is returned from `Amplify.API.mutate(request: .delete(someObject)) { event in` is:
"DynamoDB:ConditionalCheckFailedException"

Aside from not being able to delete the object, I also find it cumbersome to have to query the object first to delete it.  Ideally I just want to pass the object ID and delete it.

How can I do this?

**Comment by lawmicha** [comment]
Hi @alionthego,

What Amplify CLI steps did you take to provision your API? Did you happen to enable it with conflict resolution?

if you have conflict resolution enabled, or "Enabled for DataStore", then you'll need to use DataStore APIs to save the models to the local store, and DataStore will handle synchronizing those items to your remote store (AppSync). One reason why you may be getting ConditionalCheckFailedException may be due to the API requiring the version to be passed in. You can see if you can get a successfull request going through `amplify console api` -> GraphQL -> to launch the AWS AppSync console -> Queres tab, and perform the delete mutation using a document string and variables. if you can see the selection set requires the version, and you can query for the model with the version field returned, then deleting it with the same version value should work.

If you are trying to use API without DataStore, then you should provision the API without conflict resolution enabled. You can do this through `amplify add api` and choose No when asked to enable conflict resolution, you can use the static builders to help create the GraphQLRequest as you have in your code snippet. The rest of them are located here: https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+Model.swift

If you are trying to delete but find it cumbersome, we can definitely take this as a feature request to expose an API like

```swift
public static func delete<M: Model>(_ modelType: M.Type, byId id: String) -> GraphQLRequest<M?> 
```

In the meantime, instead of querying for the model, and you have the `id` already, then you can create an dummy model object and pass that in:
```swift
let someObject = SomeObject(id = "idToDelete")
Amplify.API.mutate(request: .delete(someObject)) { event in
}
```

Hope that helps, let us know if you are still seeing issues.

**Comment by lawmicha** [comment]
adding `documentation` label to improve the docs over at https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/ios we should have an example to delete the model

**Comment by lawmicha** [comment]
related docs improvement PR: https://github.com/aws-amplify/docs/pull/3288 includes mention of using `.delete`

**Comment by alionthego** [comment]
Hi.  I have disabled conflict resolution and I am not using Datastore.  I am managing my own local storage.
As for the Version, I am not using @versioned as it does not work with iOS API at the moment.  I have included my own version field however I am including the correct version and it makes no difference.
This is effectively a join table item I want to delete which is shown below:

type UserConversation
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, delete, update] }
    ]
  )
  @key(name: "byUser", fields: ["userId", "conversationId"])
  @key(name: "byConversation", fields: ["conversationId", "userId"]) {
  id: ID!
  version: Int!
  owner: String
  userId: ID!
  conversationId: ID!
  createdAt: String
  updatedAt: String
  user: ServerUser! @connection(fields: ["userId"])
  conversation: ServerConversation! @connection(fields: ["conversationId"])
}

I am simply querying by id to get the UserConversation and then using the .delete as shown in the question to delete and it is now working.  

As for creating the dummy object, with many required fields I can't just simply create with ID.  I need to include other fields.  Do you mean I should create a separate extension to handle this case?  I am really at a loss as to why it's so hard to simply delete an item that I have the id to.

Thanks.

**Comment by alionthego** [comment]
Any follow up on this?  I am still not able to delete this record by any means.

**Comment by alionthego** [comment]
I have figured out what the problem was.  It had to do with the delete being performed by somebody other than the owner.  So I modified the permissions and removed delete and now it works.  thanks.
