### ISSUE TITLE
Modeling friends in Amplify (or any recursive relationship)

### ISSUE THREAD

**Issue by Mauvel98** [aws-amplify/amplify-ios#1262]
Looking around online, I have been unable to find any well documented examples of how to do this, other than here, https://github.com/aws-amplify/amplify-cli/issues/1637#issue-454362348 but even this does not seem to have any substantial traction.  

The AWS team has said that this is in their backlog, however, it seems as though this ability to make connections between the same types of objects is a very common use-case, so maybe we just haven't found a better source.

Is this still the best way to implement this? 

Our use case is trying to make a connection between user types to show friends. Is there a simpler way to implement a bidirectional connection between two same type objects?

**Comment by palpatim** [comment]
Ideally, you'd be able to just do a [self-reference](https://github.com/aws-amplify/amplify-cli/issues/4052#issuecomment-619205379). (That example shows a Tree relationship, while modeling friends would a Graph, but the idea is similar.)

Unfortunately, that doesn't work in Swift because we render models as structs, which don't directly support recursive/indirect members. The current workaround is to "join" through a second relationship model, as you would do with a [many-to-many relationship](https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections):

```graphql
type GraphNode @model {
  id: ID!
  connections: [GraphEdge] @connection(keyName: "byParent", fields: ["id"])
  value: String
}

# Models a graph edge from the perspective of the "source" or "parent" vertex.
# A bi-directional edge would need two entries, one for each side of the
# relationship.
type GraphEdge
  @model
  @key(name: "byParent", fields: ["parentID", "childID"]) {
  id: ID!
  parentID: ID!
  childID: ID!
  parent: GraphNode @connection(fields: ["parentID"])
  child: GraphNode @connection(fields: ["childID"])
}
```

A many-to-many relationship needs to store both sides of the relationship. In the case of a relationship between different models, we can structure the "join" table such that each relationship record has a distinct type ("Post" to "Editor") for example. The bi-directional relationship is then accomplished with a key for each side of the relationship. ("byPost", to return all Editors for a given Post; and "byEditor" to return all Posts for a given Editor).

In this case, since the relationship is between entities of the same type, we model the bi-directional nature by maintaining two records in the "join" table: one for each direction of the relationship. In that case, we don't need a `byChild` key, since we're maintaining both sides of the relationship as single records.

Hope this helps.
