### ISSUE TITLE
Timeout for GraphQL mutations

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1284]
I am trying to create an object using:

Amplify.API.mutate(request: .create(someObject)) { event in 
...
}

In the case where you are connected to a wifi router but no the internet, this operation does not return anything.  This is not an outlying scenario and I encounter it often in hotels or airplanes when the device automatically connects to a wifi source but has not confirmed or paid for the connection and as such is not actually connected to the internet.  

In such cases this mutation does not have any callback and that causes my app many issues.  Why is there no way to manually set a timeout for these requests or if one exists to modify it's duration?

Thanks

**Comment by brennanMKE** [comment]
@alionthego What you can use is Apple's Network framework which will allow you to monitor the network path so that if it is no longer able to connect it will report the change in status. The legacy system Apple created years ago is Reachability which has been replaced with the modern framework. See reference the [Connectivity Package] for monitoring connectivity. It includes an app that you can install on an iOS device and move out of range of your WiFi connection to see the change in status. You can also turn on Airplane Mode to cut off the connection to see the status change.

When you get the update that the network path is in a state which cannot connect your can suspend network requests. When it is able to connect again you can resume network activities. Refer to [Operations] on how you can cancel operations which are in progress. With an operation you can `cancel` as well as `pause` and `resume` so that if you expect the interrupted connection is momentary you could use the pause and resume functions. Otherwise you can cancel and later restart the operations.

[Connectivity Package]: https://github.com/brennanMKE/Connectivity
[Operations]: https://github.com/aws-amplify/amplify-ios/blob/main/OPERATIONS.md
