### ISSUE TITLE
Cannot generate AWSPinpoint eligible endpoints from iOS app

### ISSUE THREAD

**Issue by lucianthorr** [aws-amplify/amplify-ios#1307]
Hi.  I've been trying to setup AWS Pinpoint notifications using the Segments feature for a few days and cannot seem to get the pieces to work together.
I've got an APN_SANDBOX setup, I'm using the configuration @rochabr is describing in this [Issue](https://github.com/aws-amplify/amplify-ios/issues/1193) where the pinpoint is setup before `Amplify.configure()` is executed because it does not seem possible to set `endpoint.channelType` afterward.
I should also mention that this seems to conflict with the recommendations [here](https://github.com/aws-amplify/amplify-ios/issues/662). I'm not sure if it's possible to set the PinpointConfiguration with AWSCredentials, run Amplify.configure() and use APN_SANDBOX.  Maybe that's my problem?
Should I be using the pinpoint generated from the `plugin.getEscapeHatch()` or from what's declared at the beginning of the program?

Anyway, I've created a Segment that captures all endpoints and it seems to capture my devices that run the app but it does not consider them eligible even though they have Allowed Notifications.  I can use Test Messaging to directly send notifications using the device token but the endpointIDs that are being saved to Segments are not considered valid either.

Any help would be appreciated.  I've been trying to work through the Pinpoint, iOS SDK and Amplify Framework docs for a while now and I feel like I'm missing some key piece to the puzzle.  Thanks

**Comment by lucianthorr** [comment]
I should mention that I cannot seem to get the channel.optOut to change to "NONE" because I think that might be the issue.
currently setting it via 
```
pinpointConfiguration.debug = true
pinpointConfiguration.isApplicationLevelOptOut = {
    return false
}
```

**Comment by ruisebas** [comment]
Hi there! With to the changes in https://github.com/aws-amplify/amplify-ios/pull/1689, you should now be able to directly grab the `AWSPinpoint` from Analytics's  `getEscapeHatch()` in order to set up Pinpoint Notifications:

```swift
do {
    try Amplify.add(plugin: AWSCognitoAuthPlugin())
    try Amplify.add(plugin: AWSPinpointAnalyticsPlugin())
    // Other plugins...
    try Amplify.configure()
} catch {
    // Handle error...
}

if let analyticsPlugin = try? Amplify.Analytics.getPlugin(for: "awsPinpointAnalyticsPlugin") as? AWSPinpointAnalyticsPlugin {
    pinpoint = analyticsPlugin.getEscapeHatch()
    registerForPushNotifications()
}
```

Alternatively you can still create your own `AWSPinpoint` instance as you've been doing.

--- 

Regarding the `endpoint.optOut` attribute, it will be set to `"NONE"` as long as:
- `UIApplication.shared.isRegisteredForRemoteNotifications` returns `true`, so make sure you always call the `registerForPushNotifications()` method as soon as your application starts. You can find a [step-by-step guide here](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios/#connect-to-your-backend).
- `pinpointConfiguration.isApplicationLevelOptOut` is either not defined (which is the default) or returns `false` (which you seem to be doing anyway). 

--- 

And about your endpoints not being considered eligible, this can happen when you do not allow unauthenticated identities and your users have not signed in. As soon as they do, their devices should become eligible. 
You can find information on how to do [enable or disable unauthenticated identities here](https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html#enable-or-disable-unauthenticated-identities).

I'm resolving this issue due to inactivity, but please feel free to reach us again if you are still facing this problem.
Thanks!
