### ISSUE TITLE
Swift Package Manager Warning

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-ios#1336]
### Describe the bug

I'm getting the following warning:

"ignoring declared target(s) 'swift-nio-zlib-support' in the system package"

You can see that they are not supporting it anymore [here](https://github.com/apple/swift-nio-zlib-support/issues/4#event-5020820433)

Please Update the package to substitute with the new one.

Thanks

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to 'add all the packages to a new project'
2. Click on 'build'
3. See error
```

### Expected behavior

Warnings...

### Amplify Framework Version

1.12.0

### Amplify Categories

Analytics, API, Auth, DataStore, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

latest

### Xcode version

latest

### Relevant log output

```shell
Showing Recent Messages
ignoring declared target(s) 'swift-nio-zlib-support' in the system package
```

### Device

latest

### iOS Version

latest

**Comment by royjit** [comment]
`swift-nio-zlib-support` is from the underlying dependency from [Starscream](https://github.com/daltoniam/Starscream). Starscream had fixed this issue in their [latest version](https://github.com/daltoniam/Starscream/commit/fe5769f2ae5a7473261ef3c3f3ecc76f1218c601), but this requires us to depend on the next major version of Starscream.

As explained [here](https://github.com/aws-amplify/amplify-ios/issues/1290) moving to the next major version is not trivial and require a lot of work. We will update this ticket when we move to the next version of Starscream. Since this is a warning, we believe that this wont affect your app.

**Comment by royjit** [comment]
Closing this issue in favor of https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/44 .
