### ISSUE TITLE
How can I manually sync datastore?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1353]
I know this has been asked in other places but I don't see any suitable answer anywhere.

Why is there no mechanism for a user to initiate a datastore sync?  The docs don't adequately explain how often the datastore sync operation performs.  For apps that rely on updates to data and for users to ensure their data is current, such as aviation related data, there needs to be some mechanism for users to know they are actually using the most current version of their data.

For example I have data on my app that updates everyday 0600 UTC.  If a user refers to the app at 0601 UTC and needs the most updated info, how can they have confidence that their app is synced?  I would ideally like a sync button that would force the sync operation but their is no api for that.

Also, during the sync the docs say that the most recent 100 items are synced and then 1000 items in batches.  But it doesn't say what happens beyond that.  What if there are 2000 or 10,000 items?  Will they ever be synced?  And if so when.  Can you please provide specific detail on how this sync operation performs.  This is vital to using datastore.

**Comment by afern247** [comment]
Good question

**Comment by afern247** [comment]
> I don't really understand the question. Maybe I'm missing something, but there's no reason why one would want to do that.
> 
> When datastore starts, it syncs with the backend. As soon as it's running, it subscribes to live-updates. Hence it won't lose sync while it's running. Since it doesn't loose sync, how much sense would manually syncing make? - There's no difference to sync.
> 
> Looking at the example give above, updates to the backend happen 6:00. If the user starts datastore at 5:59, she'll receive updates as soon as they're provided, since her client is subscribed to all changes. If the user starts datastore at 6:01, the changes get pulled with the initial sync. Answering the question above, the confidence of the latest data comes from the combination of initial sync with subsequent live-updates.
> 
> Regarding how many items are synced - it's configurable.

What if I want to store data locally only and don't want to push it to the cloud? In rder to do this you need to exclude the API at configure() time, if you try to add it later it throws an error: you cannot add a plugging after it's configured or something like that

**Comment by alionthego** [comment]
@anatomybook 
I understand your point from a developer perspective.  But not from a user perspective.

A user doesn't understand nor should he/she understand how the app works.  They just want to make sure they have the Most current data for data sensitive apps.

If the app has not had a change to the datastore in a few days it may not sync as it's unnecessary.  But a user wants to make sure that their app is synced and the way to do that is providing a sync icon and informing them that the result of the sync is that the app is synced.

If a pilot is going on a flight and they want to make sure that they have the latest database for airports routes etc, they will want to know their app is fully synced before departing on the mission.  From what you have explained it is always in sync and I understand your point.  However the user will not and I don't see what the harm is in giving the functionality to perform a manual sync and report the time that the sync completed.  Again for the sake of the user.    At the moment what your suggesting is leading me to just have a dummy button that does nothing and when the user presses the dummy sync just return that the app is synced with present time.  But seems a bit dodgy.  Why not actually allow a sync to occur.  Is there any harm in that?

I don't believe it is intuitive from a user perspective that a chat is always synced.  I believe they still want the satisfaction of knowing they have checked at THIS MOMENT in time and know for sure their data is current.  As useless as that may seem from a developer perspective.

**Comment by anatomybook** [comment]
@alionthego 

First of all, I'd like to point out that I'm also just a user. I'm neither a developer nor I am affiliated with AWS or Amazon. I was merely throwing in my 2 cents.

Yes, I agree with you. Apps should be easy. The fewer buttons, the better. That's why I'm actually quite happy with the way things are right now, including a sync button not being necessary.

If you'd like to be sure that you've observed all past events and are subscribed to live-updates, consider observing events. More specially the `ready` event. You can make also make your code aware of changes in near-real time by coupling it to updates as described [here](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios). For more info about events, please check [here](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/ios).

Anyways, just my two cents.

**Comment by alharris-at** [comment]
@alionthego I agree w/ the recommendation above by anatomybook. Because DataStore is continuously syncing with AppSync once the app is initialized (unless the user is offline), and will re-establish connection once network connectivity is restored.

The recommendation around listening to `hub` events is sound as well, if you want to provide users w/ some visual indication of sync status, or last sync time, etc.

If you need finer-grained management of the upload/download behavior, and don't want an always-synced list of models, DataStore may not be the right offering, and using [the API library](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/ios/) directly may make more sense.

**Comment by m98** [comment]
I also can't understand why there is no way in the `DataStore` to force the sync or even disable the local storage (I mean something like `offlineSync:false`!

In my experience, when I use the `DataStore`, sometimes it syncs, and sometimes it does not! It's not predictable! Typically, it should sync the data if you are online. But in my experience,  I was online, and it usually does not sync and I needed to try a few times until it save. (Maybe something is missing from my configuration!)

I say there should be an easy way to force the sync because there are some applications that it's critical for the user to have their data stored on the cloud. That's why there is a database defined and linked to Amplify application. For example, imagine a financial or banking application. They might like to use the `DataStore` as it's convenient to use, but it's still not perfect for them because it keeps the data locally which they might prefer to not store locally because of security reasons! 

This is even important for a social media app. Imagine you "like" somebodies post today, and three days later this action is getting stored on the cloud and the other person receives the notification with a few days' delay.
