### ISSUE TITLE
Cannot access data in Amplify.List

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-ios#1413]
Hi there,
I got [feedback](https://discord.com/channels/705853757799399426/707328996995760179/885293252109013013) in the AWS Amplify Discord to open an issue on this, so here I am 😊 

**Scenario:**
We've got an existing GraphQL backend (using DynamoDB, no DataStore) created with Amplify that has been serving a React-based front end for some time now.

We are in the process of building a iOS/Swift app that will use this backend.

One thing that we're confused about is the Amplify.List objects that we are seeing when we perform a list query on a model (e.g. User), where we have connections to other models (e.g. Friend):

GraphQL schema example in the User type:
```shell
  friends: [Friend] @connection(name: "Friends")
```

In the React app, we can parse the Friends of a User straight away, after retrieving the user via a list query ; however, in the iOS app, the Friends object is represented as Optional(Amplify.List<App.Friend>), when printing to console, and there seems to be no way to get at the data.

For example, below is the function used to fetch a user:

```swift
func getUser(id: String) async throws -> User {
    return try await withCheckedThrowingContinuation { continuation in
        Amplify.API.query(request: .get(User.self, byId: id)) { event in
            switch event {
            case .success(let result):
                switch result {
                case .success(let user):
                    guard let user = user else {
                        print("Could not find User")
                        return
                    }
                    print("Successfully retrieved User: \(user.username)")
                    // demonstrate error
                    if let friends = user.friends {
                        print("I got friends!")
                        for friend in friends {
                            print("FRIEND: ", friend) // <= Error happens here
                        }
                    } else {
                        print("I got no friends!")
                    }
                    continuation.resume(returning: user)
                case .failure(let error):
                    print("Could not get User \(error.errorDescription)")
                    continuation.resume(throwing: error)
                }
            case .failure(let error):
                print("Problem fetching user\(error)")
                continuation.resume(throwing: error)
            }
        }
    }
}
```
FYI: The above handling of friends is just to demonstrate the error and not what I'd want to do.  I'd want to access friends from the User object later down the line (e.g. in a View), rather than in the fetch function.

This function works to retrieve the user, but the "connected" models (e.g. friends) are the issue we are trying to work out here.  The errors thrown are the same as below.

When trying to access friends off the User object after fetch, with something simple like this:
```swift
if user.friends != nil {
   let friends = user.friends!.compactMap($0)
   print("Friends: \(friends)")
}
```
This results in:
```console
2021-09-09 05:19:44.306681+0700 App[89434:12421122] [API] The operation couldn’t be completed. (Amplify.GraphQLResponseError<Amplify.JSONValue> error 0.)
2021-09-09 05:19:44.308366+0700 App[89434:12421122] [API] The operation couldn’t be completed. (Amplify.CoreError error 0.)
2021-09-09 05:19:44.308573+0700 App[89434:12421123] [Amplify] The operation couldn’t be completed. (Amplify.CoreError error 0.)
```

I'm thinking there needs to be some more decoding happening, or perhaps the decoding is not happening correctly, which is the feedback received on Discord.  There was also mention of a potential bug that could be causing this.

For the record, the models in the iOS app were generated per the Amplify docs, as we are re-using a previously created (now shared) backend.

The entry in the User model for friends is:
```swift
  public var friends: List<Friend>?
```
And friends looks like this:
```swift
public struct Friend: Model {
  public let id: String
  public var userId: String
  public var user: User?
  public var username: String
  public var owner: String?
  public var primaryMusicStream: String?
  public var musicStreamId: String?
  
  public init(id: String = UUID().uuidString,
      userId: String,
      user: User? = nil,
      username: String,
      owner: String? = nil,
      primaryMusicStream: String? = nil,
      musicStreamId: String? = nil) {
      self.id = id
      self.userId = userId
      self.user = user
      self.username = username
      self.owner = owner
      self.primaryMusicStream = primaryMusicStream
      self.musicStreamId = musicStreamId
  }
}
```
Lastly, the type for Friend in the original GraphQL schema is as below:
```gql
type Friend
  @model
  #@key(name: "byUser", fields: ["userId", "username", "primaryMusicStream", "musicStreamId"]) {
  @auth(
    rules: [{ allow: owner }, { allow: private, operations: [read, delete] }]
  ) {
  id: ID!
  userId: ID!
  user: User @connection(name: "Friends")
  username: String!
  owner: String
  primaryMusicStream: String
  musicStreamId: String
}
```
I hope that's enough information to convey the situation.  If not, please ask.

Thanks in advance for any guidance toward resolving this issue.

**Comment by javyduty** [comment]
Same issue here, I am also trying to get data as a list, the documentation for iOS is slim compared to others. I've even tried to create my own GraphQL requests to get past this issue by returning nested values the way that it does in the documentation but that fails with an invalid response type.

[Documentation](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios/#nested-data)

**Comment by lawmicha** [comment]
Hi @kimfucious, thanks for opening this issue and the detailed information. We can use your schema (the relevant parts) and provision AppSync and investigate the error you are seeing. For the schema, could you provide the `User` type as well? I noticed you have auth rules enabled so that will be something we'll watch out for in the investigation when loading the connected list of users friends. 

Accessing `user.friends` is internally performing a list query operation for Friend with a filter on the parent object's id (where Friend.userId = user.id). You may be able to get more debugging info from the error if you use `fetch` to explicitly perform this operation:
```swift
user.friends.fetch { result in 
  switch result {
   case .success(let friends):
   case .failure(let coreError): // check coreError.underlyingError as APIError
  }
}
```

A workaround to actually getting the data back, is to hold the user object, and when you need the friends, perform the query at that time instead of accessing `.friends`, basically resorting to https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios/ as mentioned by @javyduty. Going this route usually entails going to the AppSync console's Queries tab and ensuring the expected GraphQL document and variables return a successfull GraphQL response first, then taking that and coding it into a custom `GraphQLRequest` object builder.

**Comment by javyduty** [comment]
I've noticed that for some reason when you make the call to get let's say one user by their ID in a closure and return that object, you can then access the data that is in the returned list, in this case friends. I am doing the same thing with followers and that worked for me, getting back a list as expected
`
func getUserById(userId: String, completion: @escaping (Result<User, Error>) -> Void) {
        Amplify.API.query(request: .get(User.self, byId: userId)) { event in
            switch event {
            case .success(let result):
                switch result {
                case .success(let user):
                    guard let user = user else {
                        print("Could not find user with the id \(userId)")
                        return
                    }
                    completion(.success(user))
                case .failure(let error):
                    print("Got failed result with \(error.errorDescription)")
                completion(.failure(DatabaseError.failedToFetch))
                }
            case .failure(let error):
                print("Got failed event with error \(error)")
                completion(.failure(DatabaseError.failedToFetch))
            }
        }
    }
`
Something like that worked for our team, when you get the user back from the closure pass it into a model and you'll be able to do something like 

`print(user.firends)`

and it should print out the array of dictionaries associated with your user

**Comment by javyduty** [comment]
I've noticed that for some reason when you make the call to get let's say one user by their ID in a closure and return that object, you can then access the data that is in the returned list, in this case friends. I am doing the same thing with followers and that worked for me, getting back a list as expected
```swift
func getUserById(userId: String, completion: @escaping (Result<User, Error>) -> Void) {
        Amplify.API.query(request: .get(User.self, byId: userId)) { event in
            switch event {
            case .success(let result):
                switch result {
                case .success(let user):
                    guard let user = user else {
                        print("Could not find user with the id \(userId)")
                        return
                    }
                    completion(.success(user))
                case .failure(let error):
                    print("Got failed result with \(error.errorDescription)")
                completion(.failure(DatabaseError.failedToFetch))
                }
            case .failure(let error):
                print("Got failed event with error \(error)")
                completion(.failure(DatabaseError.failedToFetch))
            }
        }
    }
```
Something like that worked for our team, when you get the user back from the closure pass it into a model and you'll be able to do something like
```swift
print(user.firends)
```
and it should print out the array of dictionaries associated with your user

**Comment by enteleca** [comment]
The reason you are not getting the associated list is because you are only querying for the top level nest of the user. In a custom GraphQL request, you need to specify exactly what you want to be returned. You also need to have the correct decodePath with your custom GraphQL Request as well. 

Example GraphQL request:

`
query getUser {
  getUser(id: "123") {
    user {
      id
      email
      friends {
        id
        email
      }
    } 
  }
}
`

After this is routed through the decode path, your returned user should have the "friends" associated with it now. Both the user and friends will only have "id" and "email" as variables with content inside (as long as your database has content in those fields). Any other field you want you will need to specify.

**Comment by kimfucious** [comment]
HI @lawmicha,

Thanks for getting back to me on this.

> A workaround to actually getting the data back, is to hold the user object, and when you need the friends, perform the query at that time instead of accessing `.friends`, basically resorting to https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios/ as mentioned by @javyduty. Going this route usually entails going to the AppSync console's Queries tab and ensuring the expected GraphQL document and variables return a successfull GraphQL response first, then taking that and coding it into a custom `GraphQLRequest` object builder.

I actually implemented a "getUsersFriends" query, before raising this issue, as I need them pretty much the same time as I need the user.

My hope was to somehow not have to make a separate call to the backend to get the user's friends.

As I mentioned prior, iOS app is using a shared backend.  And the JS Apps using (web and Native), can access the friends object immediately upon receving the User via a query.

I guess that the SDKs are differnent in their implementation in this scenario?

If there's anything to do to make the Friends data accessible w/o a second API call, please advise; otherwise, I'll please let me know that the workaround is the only solution for what I'm trying to do.

You attention and feedback is most appriciated.

**Comment by kimfucious** [comment]
Hi @javyduty,
Thanks for your input on this issue.  It looks like you're making better progress that I am.

> I've noticed that for some reason when you make the call to get let's say one user by their ID in a closure and return that object, you can then access the data that is in the returned list, in this case friends. I am doing the same thing with followers and that worked for me, getting back a list as expected

It seems like we're trying to do the same thing with followers/friends, though you're using a completion handler, and I'm using a`withCheckedThrowingContinuation` pattern.  

That said, we're both returning the User object, so the results should be the same.

Sadly, after the following:
```swift
let user = try await amplifyActions.getUser(id: currentUser.userId)
print("friends:", user.friends as Any)
```
The result is still:
```console
friends: Optional(Amplify.List<App.Friend>)
```

**Comment by kimfucious** [comment]
> For the schema, could you provide the `User` type as well?

Hi @lawmicha, here's the User type from the shared graphQL schema:

```graphql
type User
  @model
  @auth(
    rules: [
      { allow: owner }
      { allow: private, operations: [read] }
      { allow: private, provider: iam, operations: [read] }
      { allow: private, provider: userPools, operations: [read] }
    ]
  ) {
  id: ID!
  username: String!
  defaultPlaylist: String
  homeMenu: HomeMenu
  isSubscribedOneSignal: String
  owner: String
  primaryMusicStream: String
  publicPlaylists: AWSJSON
  sharedPlaylists: AWSJSON
  screenAppearance: String
  friends: [Friend] @connection(name: "Friends")
  mobileDefaultDestinationPlaylist: AWSJSON
  savedTracks: [SavedTrack] @connection(name: "SavedTracks")
}
```

**Comment by lawmicha** [comment]
Hi @kimfucious, has-many connections in iOS are loaded lazily by using the `List` type, so by default `user.friends` will not be in memory until it is accessed. Accessing the friends, `user.friends?.count` or iterating over them will perform a list query operation for friends where it is filtered on the belongs-to field's value equal to the user's id. So internally, the lazy load basically performs this:
```
query ListFriends {
  listFriend(filter: {userId: {eq: "\(user.id)"}}) {
    nextToken
    items {
      /// ..
    }
  }
}
```

As you have described, this is failing- the reason why it is failing is because the model generated schema for Friends has the target name "friendUserId".
```
// in Friends schema
.belongsTo(friend.user, is: .optional, ofType: User.self, targetName: "friendUserId"),
```

I do not see listFriends Query on AppSync that allows a filter on `friendUserId` when performing the lazy loading of the list, so the query fails:

```
// this query fails since `friendUserId` is not valid filter argument
query ListFriends {
  listFriend(filter: {friendUserId: {eq: "\(user.id)"}}) {
    nextToken
    items {
      /// ..
    }
  }
}
```
This may be a bug in provisioning AppSync (I'm not 100% certain, as the issue may also be that code generating "friendUserId" is not correct for `@connections` with `name` field).

## option 1 `@connection` v1 with lazy load

If you need to continue with the deprecated `@connection` v1 directive (if the backend cannot be updated due to react app for example) and want to lazily load the friends, you can verify that lazy load starts working by modifying the Friend schema's to `.belongsTo(friend.user, is: .optional, ofType: User.self, targetName: "userId")`. This would be a test and it would get reverted when you run `amplify codegen models` in the future. With this option, we would need to investigate the bug further.

## option 2 `@connection` v1, eager loading, no pagination

If you need to continue with the `@connection` v1 directive but want to load the users and friends in one query (as @enteleca mentioned), you'll need to provide a custom query similar to [this](https://github.com/lawmicha/amplify1413/blob/main/amplify1413/ContentView.swift#L239):
```
query MyQuery {
          getUser(id: "\(id)") {
            createdAt
            defaultPlaylist
            isSubscribedOneSignal
            id
            mobileDefaultDestinationPlaylist
            owner
            primaryMusicStream
            publicPlaylists
            sharedPlaylists
            updatedAt
            username
            screenAppearance
            friends(limit: 10) {
              nextToken
              items {
                createdAt
                id
                musicStreamId
                owner
                primaryMusicStream
                updatedAt
                userId
                username
              }
            }
          }
        }
```
The nested selection set will retrieve the friends along with the user, and the `List<Friend>` will be decoded with the friends data. The problem I see here is if you want you need to paginate pass 1000 items, it's currently not that easy to get the `nextToken` out of the List<Friend> object. Once you have the nextToken, you would pass it back to the get User query to get the user again, but with the next page of the friends ([like this](https://github.com/lawmicha/amplify1413/blob/main/amplify1413/ContentView.swift#L271-L288)). If you don't need to paginate, then you can add a sort direction and set the limit to what makes sense to your app (the limit is max 1000).

## (recommendation) option 3 `@connection` v2, with lazy loading and pagination

If you are able to update the schema, the recommendation is to use the `@connection` directive with `keyName` and `fields` ([described here](https://docs.amplify.aws/cli/graphql-transformer/connection/)). The resulting schema would look like [this](https://github.com/lawmicha/amplify1413/blob/main/schema.graphql#L41-L79). The targetName is generated as "userId" which matches the filter input for Appsync, and lazy loading works [as expected](https://github.com/lawmicha/amplify1413/blob/main/amplify1413/ContentView.swift#L166). If you need to paginate, you can call `friends.hasNextPage()` and `friends.getNextPage()`.

Please let us know which option makes sense for your use case and we can continue discussing any blockers wit it

**Comment by kimfucious** [comment]
Hi @lawmicha,

Thanks for the awesome, detailed response.

It will take a while to work through this, so kindly leave this issue open for the meanwhile.

I'll come back to you once we've decided upon options and (hopefully) successfully implemented the changes to get this working as desired.
