### ISSUE TITLE
PrefersEphemeralWebBrowserSession is not respected in Safari Authentication session on iOS 13+

### ISSUE THREAD

**Issue by allab** [aws-amplify/amplify-ios#1445]
### Describe the bug

Our application adopts `Amplify.Auth.signInWithWebUI` method. In [Amplify v1.6.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0) your team introduced  `preferPrivateSession` flag that enables Apple `ASWebAuthenticationSession.prefersEphemeralWebBrowserSession` on iOS 13+. Please note, in our implementation this flag is enabled, but behaviour we're seeing does not match declared in [Apple Docs. ](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio)

When we launch Amplify.Auth.signInWithWebUI our web login page runs a script that is trying to set a cookie with today's timestamp. If it's able to set it, website behaves as cookies are enabled and allows user to enter their credentials, if it's not able to set it, user will be advised to change their settings. 

_Observation._ After the user enables Safari - Block All Cookies property in their iOS settings, `Amplify.Auth.signInWithWebUI` does not respect Safari setting, test cookie timestamp is being set and the user is able to complete login process. This setting will only be respected after the user visited the website in Safari browser on consequent sign in invocations.

**Problem**:  If the user has launched the website from iOS Safari browser while "block all cookies" setting was enabled, after the user disabled "block all cookies" setting, Amplify.Auth.signInWithWebUI continues to load cached page and the user is not able to sign in. 

### Steps To Reproduce

```swift
Steps to reproduce:
1. On iOS device, open Preferences - Safari. 
2. Enable Block all cookies toggle.
3. Open the login webpage in Safari browser that uses cookies
4. Open Preferences - Safari
5. Disable Block all cookies toggle.
6. Launch a mobile app that adopts Amplify - Auth module, and execute action that triggers `Amplify.Auth.signInWithWebUI` with custom provider and `preferPrivateSession` is set to `true`.
7. Observe that login webpage displays an error that cookies are disabled  indicating that Safari authentication session is loading a cached version of the webpage since Block all cookies toggle was disabled in step 5.

Please note, safari authentication session continues to load cached version until `Clear History and Website Data` action is executed from Safari Preferences.
```

### Expected behavior

Upon loading `Amplify.Auth.signInWithWebUI` with `preferPrivateSession` flag set to true, it's expected that no cached browsing data or previously stored cookies in iOS 13+

### Amplify Framework Version

1.8.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

Swift 5

### CLI version

4.27.3

### Xcode version

12.5.1

### Device

iPhone 12 Pro

### iOS Version

iOS 14.4, iOS 14.5, iOS 15

**Comment by lawmicha** [comment]
Hi @allab,

> Please note, in our implementation this flag is enabled, but behaviour we're seeing does not match declared in Apple Docs.

`Amplify.Auth.signInWithWebUI` calls down to [launchASWebAuthenticationSession](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCognitoAuth/AWSCognitoAuth.m#L368-L383) so our library isn't doing anything to the flag that is enabled. I believe the behavior you are seeing regarding cookies is related to an interaction between a system setting (Settings -> Safari -> Block All Cookies) and the behavior of the ASWebAuthenticationSession when `prefersEphemeralWebBrowserSession` is set to true. There isn't anything we can do in this case to change the behavior and would be something you would need to follow up with Apple to determine whether this is the expected behavior or a bug. You can direct the question towards Apple with a [Technical Support Incident](https://developer.apple.com/support/technical/) or in the [Developer Forums](https://developer.apple.com/forums/search/?q=ASWebAuthenticationSession+cookie).

For what it's worth, here are some of my observations, done in a simulator, and I have not confirmed that the behavior on a physical device.
- Safari App respects the Block All Cookies with expected behavior. The cookie is set and retrieved across sessions when block is off, and the cookie cannot be set or retrieved when the block is on.
- The ASWebAuthenticationSession with prefersEphemeralWebBrowserSession true in a sample app will not have access to the cookie across different webpage launches in the app. However, the launched webpage refreshed does persist the cookie. This is the same behavior regardless of the Block All Cookies setting (which seems like an unexpected behavior).

**Comment by lawmicha** [comment]
> Observe that login webpage displays an error that cookies are disabled

What i think is the web session in the app is different from the web session in the Safari app. So even if a cookie is set in the Safari session, it's not going to be available in the app. When i launch the session in the app, i read the cookies and there are none (despite having set the cookie in the Safari app session). I am able to set the cookie in the app session, but with `prefersEphemeralWebBrowserSession=true` it is not persisted when i close the web session in the app and relaunch it.

**Comment by lawmicha** [comment]
From my observation, I am always able to determine that cookies are enabled when launching using ASWebAuthenticationSession, regardless of the Safari's Block All Cookes setting. When the launched webview in the app is closed, the cookie that was persisted is deleted as when I re-launch it, the old cookie is gone

**Comment by lawmicha** [comment]
Feel free to post any follow-up you may have regarding Apple's API behavior or create a new issue if there's something else not working

**Comment by allab** [comment]
Our CL team is investigating their script to validate if cookies are enabled settings is being correctly determined on Safari under the conditions described, thank you for your input.

**Comment by diegocstn** [comment]
@allab I'm optimistically closing this, but feel free to re-open if you need additional help.
