### ISSUE TITLE
Amplify iOS - Authorization Rules w/Datastore

### ISSUE THREAD

**Issue by Masami96** [aws-amplify/amplify-ios#1456]
I added auth using the tutorial (https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/) and (I think) successfully linked a Cognito User Pool with my application (creating users in the pool allows them to be used in app and vice versa). However, when using the authorization rules (https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios/) even after switching my schema to Owner only, my app keeps populating data created by all users.

For example my schema is as follows:
```
type Course @model @auth(rules: [{allow: owner}]) {
  id: ID!
  name: String
  grade: Int
  students: [ID!]
  assessments: [ID!]
}
```
and in the application I add courses using the following method:
```
Amplify.DataStore.save(
                    Course(name: self.class_name,
                           grade: self.curr_grade.num,
                        students: [],
                        assessments: []
                    )
                )
```
So once again to clearly illustrate the issue happening:
-assume all data is empty-
User1 logs into the app
User1 creates a new Course called "Course1"
User1 can view "Course1"
User1 signs out of application
User2 logs into the app
User2 can view "Course1"
User2 creates a new Course called "Course2"
User2 can view "Course1" and "Course2"
User2 signs out of application
User3 logs into the app
User3 can view "Course1" and "Course2"

From my understanding, each user (who is unique and properly linked to a different user/email in the cognito pool) should be created each Course with an attached "owner" id and when querying the "Course" field only entries created by that particular "owner" id should be viewable. However I am new to using aws and could be missing something entirely. Any help would be appreciated! thanks.

**Comment by thisisabhash** [comment]
Hello,
As first steps, please make sure:

- You've updated your API to use Cognito User Pools as authorization mode. If not, run `amplify update api` and choose Cognito User Pool for the question `? Choose the default authorization type for the API`
- If your schema contains this line : `input AMPLIFY { globalAuthRule: AuthRule = { allow: public } }`, please either remove it or comment it. Reference:  https://docs.amplify.aws/cli/graphql/authorization-rules/#global-authorization-rule-only-for-getting-started

If you're calling `Amplify.DataStore.query()` to fetch items while being signed in as `User1`, it is [recommended](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios/#:~:text=If%20your%20app,user%20to%20another) to call `DataStore.clear()` to clear the local store during sign-in/sign-out so that data doesn't leak from one user to another. 

If you're calling `Amplify.API.query()` to fetch items, you'd notice that `Course1` will be returned in the results only when `User1` is [signed in](https://docs.amplify.aws/lib/auth/signin/q/platform/ios/#sign-in-a-user). 

Please let us know if you're still facing problems.

**Comment by lawmicha** [comment]
Hi @Masami96 please see @thisisabhash's recommendations such as clearing DataStore's local store after user has logged out. Let us know if you have other questions
