### ISSUE TITLE
Archive creates invalid ipa structure

### ISSUE THREAD

**Issue by gkaimakas** [aws-amplify/amplify-ios#1471]
### Describe the bug

I have an app structure like the following targets:

- App
- Core
- Core.Live
- CoreUI

CoreLive is linked to Core.
CoreUI is linked to Core.

App is linked to Core, Core.Live, CoreUI. 
Using SPM I added Ampliy, AWSCognitoPlugin to Core.

Before adding Amplify to our codebase everything worked as expected without any issues and we were able to archive and distribute through Testflight.

After adding Amplify and trying to archive the app, we get all sorts of errors. The ipa content that we get with Amplify added is the following:

<img width="332" alt="Screenshot 2021-10-14 at 5 31 11 PM" src="https://user-images.githubusercontent.com/1790873/137353897-dd68c456-dfb4-4782-9925-3aaabfbf6ed5.png">

What we used to get before the addition of Amplify (when everything worked) is:

<img width="466" alt="Screenshot 2021-10-14 at 5 32 55 PM" src="https://user-images.githubusercontent.com/1790873/137354013-9cae97b8-a3b6-4d32-b1c4-282aabc4c39f.png">

The errors we get upon validation are the following:

<img width="698" alt="Screenshot 2021-10-14 at 6 58 52 PM" src="https://user-images.githubusercontent.com/1790873/137354236-fc441314-5a66-4bc2-934f-63e1ede644fb.png">

I have prepared a dummy project for demo purposes where I was able to replicate the issue

[DepsTest.zip](https://github.com/aws-amplify/amplify-ios/files/7347638/DepsTest.zip)

I would appreciate every bit of help

### Steps To Reproduce

```swift
1. Open the project
2. Use a valid developer account
3. Archive
4. Validate
```

### Expected behavior

The app should archive without issues

### Amplify Framework Version

from main

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

6.0.1

### Xcode version

13 (13A233)

### Device

Archive

### iOS Version

15

**Comment by atierian** [comment]
Thanks for opening this issue and providing the demo project @gkaimakas.

The distribution error you encountered is happening because DepsTestCore is an umbrella framework, which Apple doesn't support on iOS. When DepsTestCore has an Amplify dependency, it is also dependent on the frameworks that make up Amplify.  Specifically, the issue you’re seeing is because the Amplify frameworks are being nested within frameworks folder of your DepsTestCore framework.

Your best options are to have your app pull in Amplify directly (instead of the framework depending on it), or make DepsTestCore a Swift Package instead of a framework. Either of these approaches would solve the distribution issue your facing.

There are potential workarounds to the distribution error. One such workaround would be having a run script move the nested frameworks to the app target level, or removing the nested frameworks outright. Alternatively you could manually move the framework files around the archived build before distributing it. However, in either of these cases it would still be an umbrella framework, which brings risks of other issues - including undefined runtime behavior.
