### ISSUE TITLE
DataStore Events seem to arrive in the wrong order

### ISSUE THREAD

**Issue by valzevul** [aws-amplify/amplify-ios#1607]
### Describe the bug

Hey folks, I am using [DataStore Events](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/ios/) to understand whether there is anything pending the update on the client side (or if the sync is in progress).

It comes in handy when I either interact with some legacy API, so to prevent race conditions I need to make sure it got the latest data first, or when the user logs out and I want to make sure all the data is synced properly before clearing the DataStore.

However, it doesn't seem like the events come in the correct order.

For example, given `DataStore.ready`'s description:
> Dispatched when DataStore as a whole is ready, at this point all data is available

I would expect to receive it only once during the initial launch.

However, `Amplify.configure()` causes something like that:
```
[AAA]: -> event name DataStore.networkStatus
[AAA]: -> event name DataStore.networkStatus
[AAA]: -> event name DataStore.subscriptionEstablished
[AAA]: -> event name DataStore.syncQueriesStarted
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.syncReceived
[AAA]: -> event name DataStore.syncReceived
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.syncReceived
[AAA]: -> event name DataStore.ready // <-- This is where I'd expect the DB to be ready
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.syncReceived
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.syncQueriesReady
[AAA]: -> event name DataStore.ready // <-- However this happens and I am not fully sure why
[AAA]: -> event name DataStore.syncStarted // <-- And then this sync never gets started
[AAA]: -> event name DataStore.outboxStatus // <-- It also seems like outboxStatus never gets fired when DataStore starts but instead gets send only in the end of migration
```

I guess my concern is that there seems to be no way to maintain a Boolean flag within the app that could be used to check if a sync is in progress. Or is there something I miss in the docs?

### Steps To Reproduce

1. Here is how I kick off the DataStore:

```swift
try Amplify.add(plugin: AWSCognitoAuthPlugin())
try Amplify.add(
  plugin: AWSDataStorePlugin(
  modelRegistration: models,
  configuration: .custom(
    errorHandler: { error in
      Amplify.Logging.error(error: error)
    },
    conflictHandler: conflictHandler,
    syncExpressions: [
      // a bunch of sync expressions is here
    ]
  )
 )
)
try Amplify.add(plugin: AWSAPIPlugin(modelRegistration: models))
try Amplify.add(plugin: AWSS3StoragePlugin())
try Amplify.configure()
```

2. Which leads to
- multiple `.ready` events
- single `.outboxStatus` event (in the very end)
- `.syncStarted` events after `.ready` which never get a notification that this sync has finished

### Expected behavior

- single `.ready` event
- multiple `.outboxStatus` events ([as per the docs](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/ios/#outboxstatus))
- no `.syncStarted` events after `.ready`

### Amplify Framework Version

1.18.1

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

4.5.0

### Xcode version

13.0

### Is this a regression?

No

### Device

iPhone 13 Pro - Simulator

### iOS Version

iOS 15

**Comment by dsaliberti** [comment]
This also happens with me and I'm absolutely interested on how to solve it 
And obviously kin to help on reproducing.. which is very easy TBH

@royjit Does this scenario sound somehow familiar? 

thanks in advance

**Comment by brennanMKE** [comment]
@valzevul & @dsaliberti Could you send us the schema so we can populate some data and try to repro this issue? Thanks!

**Comment by lawmicha** [comment]
Hi @valzevul, 

> when the user logs out and I want to make sure all the data is synced properly before clearing the DataStore.

What do you mean the data is synced properly before clearing the DataStore? When you clear DataStore via `DataStore.clear`, this will delete the local store and all its contents, so there's no need to wait for the sync process to complete.

For
```
[AAA]: -> event name DataStore.syncReceived
[AAA]: -> event name DataStore.ready // <-- This is where I'd expect the DB to be ready
[AAA]: -> event name DataStore.modelSynced
```
The `.ready` event is fired at least after all the models have been synced (after `.modelSynced`'s). Can you confirm, this is from the logs and it shows an earlier `.ready` event? If so, it appears to be a bug.

For
```
[AAA]: -> event name DataStore.modelSynced
[AAA]: -> event name DataStore.syncQueriesReady
[AAA]: -> event name DataStore.ready // <-- However this happens and I am not fully sure why
[AAA]: -> event name DataStore.syncStarted // <-- And then this sync never gets started
```

This sequence looks correct. `syncStarted` does look confusing from its event name and isn't when "sync started", `.syncQueriesStarted` indiciates when the sync started, and `.syncStarted` is fired after the base/delta sync has completed and the sync process begins receiving subscription events. 

The ordering of hub events may come out of order by the time the caller receives it. However, some events are sent based on other events in the system, which still doesn't guarantee their ordering received by the hub listeners. Instead of validating the ordering of events, the app can react to `.ready` or `.modelSynced` to perform queries. For example, if you can only display data once the local store has been fully updated, you can react to `.modelSynced` of that model or `.ready` for the entire system.

A rough sequence of events is
1. `DataStore.start()` is called, or any DataStore operation for that matter as it will reinit the sync engine as well
2. Sync engine starts, and clears out any old mutation events.
3. Establish the subscriptions for real-time updates, however do not process the events until later. (Event: `subscriptionsEstablished`)
4. Reconcilliation via base/delta sync queries to get remote data and update local store. (Event: `.syncQueriesStarted` followed by many `.syncReceived(MutationEvent)` events)
5. the sync queries are performed in serial based on the model relationships (ie. models with association, parent synced before the child) (Event: `.modelSynced(ModelSyncedEvent)`)
6. All models have been reconciled `.outboxStatus(isEmpty: true)` and have been synced to local store (Event: `.syncQueriesReady`)
7. Begin processing subscription events (Event: `.syncStarted`) and emit the `.ready` event.

Hope this clears up some of the confusion. Please let us know if you have more information on reproducing the duplicate `.ready` event @dsaliberti

**Comment by harsh62** [comment]
Closing the issue due to inactivity. If this issue still persists, please reopen the issue.

**Comment by dsaliberti** [comment]
it really helped me to address one issue on our side 
However [it seems there's more happening after signOut+signIn](https://github.com/aws-amplify/amplify-ios/issues/1764) in the same run @lawmicha 
Thanks
