### ISSUE TITLE
observeQuery is providing multiple versions in the receiveValue items

### ISSUE THREAD

**Issue by kddejong** [aws-amplify/amplify-ios#1632]
### Describe the bug

When trying to understand why `print("[Snapshot] item count: \(querySnapshot.items.count), isSynced: \(querySnapshot.isSynced)")` was returning more items than in the dynamodb table I noticed I was getting back duplicates for the same ID. It would appear that quick upstream mutations are causing duplicate records to be returned and the `isSynced` property will be true even with those duplicate IDs 

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Setup a model and sync it to the DataStore
2. Initiate mutations and watch the DataStore count change
```

### Expected behavior

I would expect any items returned by observer query to be unique based on the ID and that the count matches the active records in the database.

### Amplify Framework Version

1.19.2

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

7.6.8-geo.0

### Xcode version

13.2.1

### Is this a regression?

No

### Device

Iphone

### iOS Version

13

**Comment by lawmicha** [comment]
Hi @kddejong, observing changes to the local store due to `DataStore.save` operations sent from the same app will result in two events, one due to the change to the local store from the SQL insert/update operation, and a second due to the mutation sent to the remote store which is reconciled against the local store from the corresponding subscription event. Emitting two snapshots for the same item would be the expected behavior, and is also the same behavior as the `DataStore.publisher` API for observing item changes (which is used internally by DataStore.observeQuery to generate snapshots).

The two snapshots received for the same item that was changed should have the same snapshot and the count should also be the same. I understand having two snapshots due to locally sourced saves may seem redundant and would be interested to hear if this behavior is causing an issue for you to build your app against

If the `count` is not accurate then that is a data integrity issue. Do you have logs that indicate this? I'm suspecting that it may seem like the count was not accurate amidst the duplicate snapshots. I believe doing a `DataStore.query` to get all the items from SQL should match the count of the snapshot. DataStore.observeQuery is mostliky a wrapper around two existing APIs, it first performs an initial `DataStore.query` to get the current state of the local store into memory, then for any item change observed from `DataStore.publisher`, it will keep the in-memory snapshot up to date.

**Comment by harsh62** [comment]
Closing the issue due to inactivity.
