### ISSUE TITLE
Datastore ready status very slow

### ISSUE THREAD

**Issue by DanielZanchi** [aws-amplify/amplify-ios#1650]
### Describe the bug

At the first launch of the application I try to perform a query to get information to display on the homescreen:

in my app delegate I configure Amplify:
```
        let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())
        let apiPlugin = AWSAPIPlugin(modelRegistration: AmplifyModels())
        
        do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.add(plugin: dataStorePlugin)
            try Amplify.add(plugin: apiPlugin)
            try Amplify.configure()   
        } catch {
            print("Could not initialize Amplify: \(error)")
        }
```

Then **I start DataStore** and **wait for the ready event** before performing the query <- Since at first launch the app doesn't have any data in local.

```
Amplify.DataStore.start { (result) in
                switch result {
                case .success:
                    print("DataStore started")
                    self.eventListener = Amplify.Hub.listen(to: .dataStore) { (payload) in
                        if payload.eventName == HubPayload.EventName.DataStore.ready {
                            print("Datastore is ready")
//PERFORM THE QUERY TO DISPLAY TO HOMESCREEN OF THE APP
```

The issue is that the "Datastore is ready" gets printed after more than 80 seconds.

I have a stable wifi connection.

### Steps To Reproduce

```swift
-
```

### Expected behavior

At first launch it's ok to wait 4-8 seconds for the DataStore to be ready, not 80 seconds. 

### Amplify Framework Version

1.21.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

7.6.21

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 13 Pro

### iOS Version

iOS 15

**Comment by lawmicha** [comment]
Hi @DanielZanchi, could you share the schema and number of items for each model in the schema you are syncing on a fresh app launch? If your listening to the hub events, you can see how many items are synced for one particular model from the `.modelSynced` event. The data in the payload is `ModelSyncedEvent`. With more information about your use case, we prioirtize on the bottlenecks that are directly impacting you. Instead of waiting for the `.ready` event, you can try performing the query after it's corresponding `.modelSyncedEvent`. For example, the events should come in this order:

1. modelSynced(model1)
2. modelSynced(model2)
3. modelSynced(model3)
4. ready

You can also try out [DataStore.observeQuery](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios/#observe-query-results-in-real-time) to get snapshots of the data while it is syncing, if you are okay with showing some data while knowing that the snapshot does not represent the entire dataset from the remote store.

**Comment by DanielZanchi** [comment]
I ended up not using DataStore but using GraphQL API calls to get data from dynamoDB. I found out that the database was getting big and waiting for it to ready was too long.

**Comment by lawmicha** [comment]
Thanks for the follow up! Feel free to open another issue if you have any questions using the API.

**Comment by diyajohnc** [comment]
I need to use datastore as my app supports offline scenarios. But ready event is getting too much time as the db is getting bigger.
Any solution for this
