### ISSUE TITLE
Adding non-optional fields to the schema definition breaks sync to the cloud.

### ISSUE THREAD

**Issue by morisobaa** [aws-amplify/amplify-ios#1784]
### Describe the bug

Hello, I have a question.
I am using DataStore with Amplify.

After adding a required field to the schema definition, I am unable to sync with the cloud.
I have updated PostTags in 
```
# Schema v1
type Post @model {
  id: ID!
  title: String!
  tags: [PostTags] @hasMany
}

type Tag @model {
  id: ID!
  label: String!
  posts: [PostTags] @hasMany
}

type PostTags @model {
  id: ID!
  post: Post! @belongsTo
  tag: Tag! @belongsTo
}
```
to
```
# Schema v2
type Post @model {
  id: ID!
  title: String!
  tags: [PostTags] @hasMany
}

type Tag @model {
  id: ID!
  label: String!
  posts: [PostTags] @hasMany
}

type PostTags @model {
  id: ID!
  option: String! # UPDATED FIELD
  post: Post! @belongsTo
  tag: Tag! @belongsTo
}

type Parent @model {
  id: ID!
  children: [PostTags] @hasMany
}
```
.
I dare not use @manyToMany.

The following error was displayed when the log level was set to debug.
```
[ProcessMutationErrorFromCloudOperation] Unhandled error with errorType DynamoDB:DynamoDbException
```

There is no problem to sync schema that has not been updated.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Define schema v1
2. Run 'amplify codegen models' and 'amplify push'
3. Update schema to v2
4. Run 'amplify codegen models' and 'amplify push'
5. Execute DataStore.Clear() and delete all PostTags objects on dynamoDB
6. Create a PostTags object
7. See the error
```

### Expected behavior

Local and cloud are synced.

### Amplify Framework Version

8.0.1

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

swift-driver version: 1.45.2 Apple Swift version 5.6

### CLI version

8.0.1

### Xcode version

13.3(13E113)

### Is this a regression?

No

### Device

iPhone12 Simulator

### iOS Version

iOS 15.4

### Additional context

- DataStore auto-merge is enabled
- GraphQL

**Comment by morisobaa** [comment]
I just edited and added Parent model to schema v2.
This is the correct information.

**Comment by morisobaa** [comment]
I solved the problem myself, but the auto-generated code seems inappropriate.

The @hasMany causes PostTags to auto-generate an optional field named parentChildrenId.
If I create PostTags with nil parentChildrenId, it is not possible to sync.

Shouldn't parentChildrenId be auto-generated as a required field?

**Comment by harsh62** [comment]
@morisobaa Thanks for providing an update. Our team is currently investigating the issue and will provide an update soon.

**Comment by lawmicha** [comment]
Hi @morisobaa, glad to hear you were able to solve the problem with the schema upgrade scenario. If you could let us know how did you solve the `DynamoDB:DynamoDbException` issue? If you cleared the DynamoDB tables of all the entries, then I would expect the service to be in a clean state to perform mutations for the updated schema. For a DataStore conflict resolution enabled API, there are some extra tables like the delta table, so I think those would need to be cleaned up as well.

Regarding use of `@hasMany` from TransformerV2, I recall `PostTags` does not need to be defined and instead of using two `hasMany`, you can use `manyToMany` directive. One example I've tried before is https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TransformerV2/DataStoreConnectionScenario5V2Tests.swift 

I see also have the Parent model with has-many PostTags, which is something I haven't tried myself, but if we know the auto generated join table name then could something like this work? (I have not tried out the below schema if that works)

```
# Schema v2
type Post @model {
  id: ID!
  title: String!
  tags: [Tag] @manyToMany(relationName: "PostTags")
}

type Tag @model {
  id: ID!
  label: String!
  posts: [Post] @manyToMany(relationName: "PostTags")
}

type Parent @model {
  id: ID!
  children: [PostTags] @hasMany
}
```
reference https://docs.amplify.aws/cli/graphql/data-modeling/#many-to-many-relationship

**Comment by morisobaa** [comment]
The cause of this error is most likely not a schema update and the title of the issue needs to be changed.

It is caused by creating a PostTags model with parentChildrenId of nil.

**Comment by morisobaa** [comment]
@manyToMany does not allow adding custom fields. For example, "option" in the above schema v2.

I think the schema shown by @lawmicha works.

**Comment by lawmicha** [comment]
I believe there is some limitations working with optional fields as you've seen. In iOS code, it should work by treating optional fields as required fields, or better yet to update the schema to make the optional fields required so that the code generated types have required fields for you to write app code against. 

In regards to adding custom fields to the many-to-many model, i think you'll get some more insight if asked in the cli repo https://github.com/aws-amplify/amplify-cli . Let us know if you have more questions or issues

**Comment by lawmicha** [comment]
For associations which are optional, we've got a change here to address the issue https://github.com/aws-amplify/amplify-ios/pull/1849 please track that for the release or if you have a schema with optional associations you can try the fix out from `fix/optional-associations` . Let us know if you have more questions and feel free to open a new issue with your latest schema and any issues you are seeing
