### ISSUE TITLE
Amplify 1.26.2 - Compilation issue

### ISSUE THREAD

**Issue by stephanemouawad** [aws-amplify/amplify-ios#2001]
**Describe the bug**
It's impossible to archive my iOS framework in command line when I use Amplify

**To Reproduce**
- install Amplify, AmplifyPlugins/AWSAPIPlugin and AmplifyPlugins/AWSCognitoAuthPlugin with cocoapod
- Run the following cli: xcodebuild archive -workspace xxx.xcworkspace -scheme xxx -sdk iphoneos -archivePath 'ios_devices.xcarchive' -configuration release BUILD_LIBRARY_FOR_DISTRIBUTION=YES SKIP_INSTALL=NO

**Stack Trace**
error: 'let' property 'convert' may not be initialized directly; use "self.init(...)" or "self = ..." instead
        self.convert = converter
             ^
SDK/Pods/Amplify/Amplify/Categories/DataStore/Model/Temporal/SpecBasedDateConverting.swift:18:18: note: 'convert' declared here
    internal let convert: DateConverter

**Areas of the SDK you are using**
_**Amplify**_ <- The error is here
AWSMobileClient
AppSyncRealTimeClient

**Environment(please complete the following information):**
 - SDK Version: iphoneos15.5
 - Dependency Manager: Cocoapods
 - Swift Version : 5
 - Xcode Version: 13.4.1 (13F100)

**Device Information (please complete the following information):**
User defaults from command line:
    IDEArchivePathOverride = /xx/xx/xx/xx/xx/ios_devices.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    BUILD_LIBRARY_FOR_DISTRIBUTION = YES
    SDKROOT = iphoneos15.5
    SKIP_INSTALL = NO

**Comment by atierian** [comment]
Thanks for opening this issue @stephanemouawad. Can I ask why you're building with `BUILD_LIBRARY_FOR_DISTRIBUTION` set to `YES`? Doing so enables library evolution mode for your framework. This, in turn, requires all dependencies of that framework to support library evolution mode as well. Library evolution mode comes with a lot of constraints and is not supported by Amplify iOS.

**Comment by atierian** [comment]
Hey @stephanemouawad, a quick update since it's been over a week. I'm still looking into this. I haven't been able to reproduce exactly what you're experiencing, but I am running into failures when `BUILD_LIBRARY_FOR_DISTRIBUTION` is set to true. I'll follow back up here once I have an update. Thanks for your patience.

Can you please clarify if this is a regression; were you able to archive with these build settings with previous versions of Amplify?

**Comment by stephanemouawad** [comment]
Hi @atierian I don't think this is a regression to be honest.
We just used both AWSMobileClient, AWSCognitoIdentityProvider and everything was working fine. Recently, we decided to capitalized the AWS SDK as much as possible. I noticed this problem when adding Amplify + required dependencies.

In short, we were not using Amplify until now.

Maybe the sdk is not ready to support this **flag**  yet ? When I check the link bellow, some dependencies are not provided as binaries.

https://github.com/aws-amplify/aws-sdk-ios/releases

All SDK download by our project
Installing AWSAuthCore 2.27.12 <<<<<================== Available in xcframework
Installing AWSCognitoIdentityProvider 2.27.12  <<<<<======= Available in xcframework
Installing AWSCognitoIdentityProviderASF 2.27.12  <<<<<==== Available in xcframework
Installing AWSCore 2.27.12  <<<<<===================== Available in xcframework
Installing AWSMobileClient 2.27.12  <<<<<=============== Available in xcframework
Installing AWSPluginsCore  <<<<<===================== Available ??
Installing Amplify <<<<<============================  Available ??
Installing AmplifyPlugins <<<<<======================= Available ??
Installing AppSyncRealTimeClient <<<<<================ Available ??

**Comment by atierian** [comment]
I was just able to reproduce what you're experiencing, and can finally make some sense of it. I needed to add a `post_install` instruction in the Podfile to set the pods' `config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION']` to `'YES'`. I presume you also had this setting enabled?

Your assumption is correct. We only provide Amplify as source, not as a binary, and we don't provide library evolution support. Doing so would force us to provide a stable binary interface, which would be extremely limiting and come with some significant negative consequences. 

Interestingly enough, that error you're seeing is completely inaccurate; that code should compile. It appears the `@inlinable` / `@useableFromInline` attributes are tripping up the compiler in this particular case when `BUILD_LIBRARY_FOR_DISTRIBUTION` is enabled.

I see three different options for you here:
1. Distribute your framework as source rather than an `xcframework`.
2. Make intermediate wrapper framework that wraps Amplify, imports it only using `@_implementationOnly` so that your wrapper doesn't publicly expose Amplify's ABI. e.g. `@_implementationOnly import Amplify`.
3. Delete all occurrences of the following within Amplify. `@inlinable`, `@useableFromInline`, `@inline(never)`. This should allow you to build Amplify with `BUILD_LIBRARY_FOR_DISTRIBUTION` enabled. However, it will also regress the performance around that code (currently limited to date formatting / decoding).

I'd recommend the first option, but I understand that may not be an option for you. If that's the case, the second option could work for you. It depends on a "non-blessed" attribute, which is only supposed to be used within the Swift standard library according to official guidance. Theoretically the behavior of that attribute (`@_implementationOnly`) could change at any time, practically that is very unlikely to happen. If that risk is acceptable to you, you could consider that path. The third option really isn't great; you'd need to delete those attributes again every time you update Amplify.

Let me know if you have any questions and thanks again for your patience.

**Comment by stephanemouawad** [comment]
Thank you for your response and your time, we will try to make a trade-off between option #1 and #2.
Stéphane

**Comment by marvukusic** [comment]
Hi,
We were struggling a bit for a while and came up with #2 solution for our framework.

Next issue we encountered is that amplify sub dependencies would be missing from final product resulting in runtime errors.
Workaround was to install those dependencies (basically, old AWS libs) manually in host project that consumes our framework.

**Comment by atierian** [comment]
That's great to hear. Thanks for sharing!

**Comment by stephanemouawad** [comment]
I tried all the solutions 

Here is my personal feedback.

- The first option is by far the easiest way to solve this issue (what I did).
- The second one does not work at all **@_implementationOnly import Amplify**.
- The last one "Removes all occurrences of the following in Amplify. @inlinable, @useableFromInline, @inline(never)" works fine but is inconvenient and not recommended if you want to benefit from/of runtime performance. 


I am curious to know how @marvukusic solves this. If you can provide us a sample :)

**Comment by marvukusic** [comment]
@arkeri @stephanemouawad 

To build a binary framework which contains Amplify as a sub dependancy do the following:

1. Add Amplify package with needed products using SPM to a framework project
2. Use `@_implementationOnly import Amplify` where needed inside a framework project
3. Create a binary of a framework
4. Check Amplify sub dependancies (`AWSiOSSDKV2` package) for needed products within Amplify package manifest and write them down (AWSCore, AWSS3, AWSMobileClientXCF etc.)
5. Distribute binary framework (using SPM or manually) and install missing dependancies

Manual distribution: install `AWSiOSSDKV2` package with needed products using SPM in project that is using a binary framework.

Distribution through SPM: use package manifest to auto-install AWSiOSSDKV2` package with needed products.

**Comment by lindrrow-gh** [comment]
Hi @stephanemouawad may I ask, what steps did you do to do the step 1? I'm using flutter but I'm having the same error when enabling BUILD_LIBRARY_FOR_DISTRIBUTION.
