### ISSUE TITLE
List Usability - List only returns up to 1000

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#27]
List API usability testing is required.

Currently in line with JS library; uses LLC s3 to retrieve list of keys. 

According to S3 documentation, only returns 1000 items.

This issue is test usability of List API, document any limitations (like the 1000 returned items) and make any changes necessary to the usability that we want

**Comment by jamesonwilliams** [comment]
I think we should decide on a consistent list/query paradigm across all of our categories. One possibility is to always return an iterator/iterable, so that we can do pagination under the hood, on behalf of the user, if they seek `next()` beyond a page boundary:

```
Amplify.Storage.list(
    bucketUri,
    iterator -> {
        while (iterator.hasNext()) {
            Log.i(TAG, "Item: " + iterator.next().toString());
        }
    },
    error -> Log.e(TAG, "Failed to get items from storage.", error)
);
```

If we _don't_ do that, then we should provide the user with a way to handle their own pagination, and perhaps just give them back a collection/list:
```
Amplify.Storage.list(
    bucketUri,
    pagingToken, // Nota Bien!
    results -> Log.i(TAG, "Got back a collection of " + result.size() + " results."),
    error -> Log.e(TAG, "Failed to get any results.", error)
);
```

**Comment by lawmicha** [comment]
thanks for the comment, i've moved this over to pivotal and referenced this issue for the context. closing this out to track on pivotal
