### ISSUE TITLE
Pass new user agent prefix for Amplify calls

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#271]
Currently the API category uses a user agent specified in a constants file (see #75). We need to update this:

- Use exact same user agent pattern as we do in the iOS SDK (https://github.com/aws-amplify/aws-sdk-ios/blob/afcce622023a8885ebfc676f6c83e6db8e7d7915/AWSCore/Service/AWSService.m#L158), except change the prefix to "amplify-iOS" instead of "aws-sdk-iOS": `amplify-iOS/<version> <systemName/<systemVersion> <locale>`

- Use the user agent for all calls into AWS services, not just API calls. This means we'll have to plumb the user agent string to be overwritable by Amplify calls, but not universally overwritable. We'll need to discuss the best way to do this.

**Comment by lawmicha** [comment]
@royjit 's previous work https://github.com/aws-amplify/amplify-ios/pull/166

**Comment by wooj2** [comment]
I did a deep dive last week of the user-agents we have been sending out.

# Currently in Production:
## AWS SDK iOS
Constructed as part of AWSCore, the user agent looks like the following:
```
    "aws-sdk-iOS/<version> iOS/<iosVersion> <locale>"
```
(Note that there can be some variations if you look at line 179 of AWSService.m)
 
## Amplify Storage/Predictions & other categories using the AWS SDK iOS (BUT NOT Amplify API/DataStore)
Since Jithin’s PR has not been pushed to mainline yet, the user agent should be using the same user agent as the AWS iOS SDK, so therefore, it should be:
```
    "aws-sdk-iOS/<version> iOS/<iosVersion> <locale>"
```
## Amplify API (and Amplify DataStore):
When using IAM or userPools, the user agent is:
```
    "amplify-ios/0.9.0 Amplify"
```
 
When using an APIkey, we are not setting the user agent (this is a bug, and we need to fix this)
```
    Currently a bug, and will need to get fixed
```

 
## AppSync
Based on this link: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/master/AWSAppSyncClient/AWSAppSyncHTTPNetworkTransport.swift#L114
We seem to be sending out a user agent of:
```
    “aws-sdk-ios/3.0.0 AppSyncClient"
```

# In the short term (prior to P31016485 getting resolved -- e.g. backend parsing being completed):
We recommend two immediate changes.
1.  Change Amplify API user agent from:
```
“amplify-ios/0.9.0 Amplify”
```
To:
```
"aws-sdk-iOS/2.12.2 iOS/<iosVersion> <locale>"
```
We believe that by making this change, the metrics team will be able to provide us some basic usage metrics (despite not being able to differentiate between actual SDK usage vs amplify usage)
2.  Fix the bug in Amplify API to set the user-agent when using an API key.
 
 
 
# Longer term (but hopefully not too long)
Sit down with the metrics team to agree on a format for the user agent we send from the amplify clients to the backend services so that we can clearly attribute calls from amplify vs calls from AWS SDK iOS.
Make appropriate changes & test

**Comment by wooj2** [comment]
Sync'ed with Mohit from the product side, we have decided that
1.  We will not be doing a "short term fix"
2.  the desired user agent on iOS will be in the following format:
```
amplify-iOS/<version> <systemName>/<systemVersion> <locale>
```

**Comment by wooj2** [comment]
WIP PR here: https://github.com/aws-amplify/amplify-ios/pull/273

**Comment by wooj2** [comment]
![VerifyViagraphqlRequest](https://user-images.githubusercontent.com/1911939/71386988-5b03dc80-25a6-11ea-9bee-dff98482ccc8.png)

**Comment by wooj2** [comment]
Verification of building storage api into a sample app and making a storage call
![verifyStorage](https://user-images.githubusercontent.com/1911939/71389131-fc436080-25af-11ea-92bb-35fd4ad899ee.png)

One thing i did notice however is that when we authenticate via codigo, we are continuning to use the aws-sdk-ios user agent from that call, but i suppose that is expected.

**Comment by wooj2** [comment]
Three more items we should verify w/ charles proxy prior to closing this issue:
* API-REST calls
* Predictions
* Pinpoint

**Comment by wooj2** [comment]
Verification of predictions calls:
![verifyComprehend](https://user-images.githubusercontent.com/1911939/71422679-dada8700-2638-11ea-9c89-c86cc4cf65c1.png)
![verifyTextTranslate](https://user-images.githubusercontent.com/1911939/71422680-dada8700-2638-11ea-9148-69ee5d5d11c8.png)
![VerifyRecognition](https://user-images.githubusercontent.com/1911939/71422681-dada8700-2638-11ea-8178-359d12b58c6d.png)

**Comment by wooj2** [comment]
Verified with api w/ apikey... didn't verify other mechanisms, but based on how the code is structured w/ interceptors, we should be good to go on the API category.
![Verify_API_REST_APIKEY](https://user-images.githubusercontent.com/1911939/71423659-bc2bbe80-263f-11ea-86db-93abeaca0eb6.png)

**Comment by wooj2** [comment]
Verified pinpoint:
![verifypinpoint](https://user-images.githubusercontent.com/1911939/71424193-51c94d00-2644-11ea-934e-81bc5006fa12.png)


manually verified each of the categories, lgtm!
