### ISSUE TITLE
Convert snake case (SQL) to camel case (GraphQL)

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-ios#274]
**Which AWS Services is the feature request for?**
Amplify code generator

**Describe the solution you'd like**
Usually, SQL databases use snake case, while usually GraphQL schemas use camel case.
If the database uses snake case, Amplify generates the entire GraphQL with snake case, which is not very nice.
A solution would be to generate the proper code in the templates (requests and responses). I don't know who though.

**Is your feature request related to a problem? Please describe.**
It is not a problem.
In iOS, when we convert json files to data models (or the other way) using Codable, we have a flag to map those 2 names styles automatically.
Would be nice to have the same here.
https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase

**Describe alternatives you've considered**
My alternative is to move the problem to the data base and use camel case there, which is not very nice.
Any other idea?

**Comment by drochetti** [comment]
Hey @Ricardo1980, this is not a feature we're currently considering. Can you provide more info on how are you defining the _snake_case_ properties?

Given that the `schema.graphql` is the single source of truth for the data model in both `API` and `DataStore`, are you defining properties with _snake_case_ in your schema and want them converted to _camelCase_ in Swift generated models?

**Comment by Ricardo1980** [comment]
@drochetti 
@palpatim 
This is the problem I see:
When using graphql and dynamodb, very often you generate the db from the graphql schema, that is, the db will have the names you wrote previosly in the graphql schema.

When using RDS, this is not the case, in fact, it is impossible. You already have to have a db and then amplify generates the templates from the db. The thing is, in mysql dbs and similar, people use snake case, not camel case, most of the time. Just check any mysql, oracle, or any other relational db nowadays.

In my case, because I created a new aurora serveless db for my project and I have total control, I renamed everything using camel case to fix this issue (so, now my graphql schema uses camel case), however, for some people this is not not always possible.
How can you integrate appsync with an already existent rds db? Unless you map all fields, one by one, in your VTL templates or use AS, then you cannot use it. And if you do that, it is very annoying that you cannot use "select * from...." or adding a new field.
In iOS, to solve these problems (legacy web services integration) and avoid writing a lot of boiler plate code, we have this:
https://www.hackingwithswift.com/articles/52/swift-4-1-improves-codable-with-keydecodingstrategy

Perhaps you can do something similar.
It is a suggestion very useful for people that use RDS.
Something in the Swift generator. I mean, the VTL use the original naming, and then a flag the user passes to the swift generator changes this, like Decodable.

Perhaps the question should be: how many people are using rds rather than dynamodb and having a similar problem. So you can take a proper decision.

Let me know your thoughts.
Thanks a lot.

**Comment by drochetti** [comment]
Hey @Ricardo1980 thanks for the thoughtful follow up.

First, I want to make it clear that I do understand the difference in naming pattern between GraphQL and Relational DBs. I believe the question here is not _if_ but _where_ that mapping should happen.

Making Swift adapt to the naming conventions means all the other platforms will have to have a similar mechanism in place. That said, since the database integration happens at the AppSync level, this seems like a feature AppSync should handle as the source of truth and platforms don't have to be aware of a database implementation detail.

> Perhaps the question should be: how many people are using rds rather than dynamodb and having a similar problem. So you can take a proper decision.

From the iOS perspective we don't have many, but the question here is more from the AppSync perspective. Like I said above, I believe that's where naming conventions should be handled so the GraphQL clients don't need to worry about that.

**Comment by Ricardo1980** [comment]
@drochetti 
Yes, I agree, evidently, Android developers have the same problem and you don't want the same logic repeated in 2 code generators (swift and kotlin). I didn't think about this case.
However, afaik there is only one layer remaining, the VTL templates. Somehow, the code generated in the request and the response has to manage that. It shouldn't require any change if you use the same naming convention, but if that is not the case, then you generate extra logic there (which is reused by js, android, ios...).
How do you pass this info to appsync with this approach? (the naming convention you want to use, in fact, it could be detected automatically most of the time, unless those crappy db with different naming conventions, which is also a third scenario).
What about when adding, renaming, removing a field if VTL generates code to map all fields, one by one? The developer should have to modify a lot of autogenerated code.
That means when cannot use "select * from..." in the VTL requests, which slows down the development cycles.
Don't know, just some ideas. Maybe that is the only possible solution.
Perhaps you need a low priority task to solve this. Maybe in the future amplify is more popular and more legacy systems need this.
In my case, it is already solved it, not the way I wanted, but it is working.
You can close the ticket if you prefer, or change the priority.

**Comment by drochetti** [comment]
@Ricardo1980 thanks again for providing this feedback and details of your use case and workaround.

I just reached out to the AppSync team to pass this feature request on to them and make sure they're aware of this feedback. I linked this issue and also provided my take on it. The feature request is now in their backlog.

For the time being I'll close this issue since there's not much we can do on iOS alone. Stay tuned on AppSync announcements because they told me some VTL string utilities will be launched soon, which might not be perfect to sole this, but it will make it easier.

Feel free to reach out to us again if you come across any other issue and/or feedback you might have.
