### ISSUE TITLE
which policies to add - is not authorized to perform: amplify:CreateApp on resource

### ISSUE THREAD

**Issue by prmacias** [aws-amplify/amplify-ios#304]
**Describe the bug**
I am following the tutorial here and my goal is to get AWS Transcribe in ios app. 

https://aws-amplify.github.io/docs/sdk/ios/start#step-1-configure-your-app

I'm at the Step 2 - Initialize the project

I typed amplify init and got the error - 

init failed, and is not authorized to perform: amplify:CreateApp on resource.

There is no instructions mentioning how to add policies to my IAM role on this page for amplify. 

I went to the stackflow and it says that I need to add the policies (pretty lot of policies here). Not sure if it's outdated or not.

https://stackoverflow.com/questions/59734709/amplify-createapp-permission

I went to the IAM page and started to see what roles I can find by that answer -

"appsync:*", 

and I see the 

AWSAppSyncAdministrator
AWSAppSyncInvokeFullAccess
AWSAppSyncPushToCloudWatchLogs
AWSAppSyncSchemaAuthor

Not sure what policies to add to get it working.

**To Reproduce**
I typed amplify init and got the error - 

init failed, and is not authorized to perform: amplify:CreateApp on resource.

There is no instructions mentioning how to add policies to my IAM role on this page. 

I went to the stackflow and it says that I need to add the roles 

https://stackoverflow.com/questions/59734709/amplify-createapp-permission

I went to the IAM page and started to see what roles I can find by that answer -

"appsync:*", 

and I see the 

AWSAppSyncAdministrator
AWSAppSyncInvokeFullAccess
AWSAppSyncPushToCloudWatchLogs
AWSAppSyncSchemaAuthor

Not sure what policies to add to get it working.

**Expected behavior**
I expect to see amplify working and start coding to get transcribe working as well.

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.13.1
 - Dependency Manager: Pods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Iphone 6s plus
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**

**Comment by kneekey23** [comment]
hi @prmacias when you installed the amplify cli on your machine, did you run `amplify configure` to set up a role? what roles are listed currently in your `~/.aws/credentials` file located at the root of your user?
There should be a role in there that looks like this:
[default] #or name of profile here
aws_access__key_id=xxxxxxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key=xxxxxxxxxxxxxxxxxxxxxx

 Find that role and see if it has permissions to create IAM policies. Usually you can just put an Admin policy on that one or PowerUser so that that role can create all the resources you need.

**Comment by prmacias** [comment]
Hello @kneekey23, thanks for the instructions, I got it working.

For the additional notes for the step 2, the amplify init will create a NEW user. I didn't do that and I created the user beforehand so it didn't have AdministratorAccess (it had Amazon Transcribe only). I went along to create a new user and it created the AdministratorAccess in the user creation in console (site) then CLI started adding the roles. 

Thanks again!

**Comment by kneekey23** [comment]
Do you mean `amplify configure`? `amplify configure`is run once when you install the cli. `amplify init` is run at the root of each project you want to use amplify for. Then you would run `amplify add predictions`and then `amplify push` to provision those resources in aws.  Please feel free to close this issue if you feel your issue is resolved. Thanks!

**Comment by prmacias** [comment]
@kneekey23 Yes, you are right, it's amplify configure - typo.

**Comment by dongnguyen01** [comment]
Could you please guide me how to use "amplify init" without AdministratorAccess (full admin access role)?
What policies should I add to my IAM user without the full admin access role?
