### ISSUE TITLE
Amplify iOS Roadmap/General Availability

### ISSUE THREAD

**Issue by jeffla** [aws-amplify/amplify-ios#335]
The docs say **Amplify iOS is in preview mode and not intended for production usage at this time.** Is there a target date for that to change to GA? 

Latest versions of everything if you are interested.

**Comment by amuresia** [comment]
Sorry to chase but could we get an answer. And apologies if I sound like I am ranting but I haven't seen much progress in the last 2 months.
There are so many problems currently in different parts of the framework that I am spending more time implementing workarounds than using basic functionality that is documented but not functional.
- analytics - don't see data
- storage - can't upload/download
- API/datastore - don't even want to start thinking about how many sleepless nights I had trying to troubleshoot and workaround object connections that don't show up in DynamoDB.
- building on a device - no longer possible

It takes an awful amount of time to get the attention of the team when an issue related to core functionality is reported. At least a rough timeline of when we can expect to go out of preview mode would really help. At this point I am really contemplating going back to the old SDK because that was **A LOT** more stable and usable ... or even using a different framework all together.

I and probably many other developers need to understand when can we look at launching our applications to production. It's not fun when you have a concept in mind and somebody beats you to releasing it to the app store, been there, done that.

**Comment by jtmorris314** [comment]
+1

**Comment by mlabieniec** [comment]
@amuresia Apologies for your frustration. We are working diligently to get the Amplify iOS libraries to GA as soon as possible. Can you share any log data around the failures you are experiencing? Also, are you using the published pods or the GitHub repository? There are a few issues we are actively working on that might relate to what you are seeing here, but without more details/logs it's hard to know what you are running into:

 - Analytics: https://github.com/aws-amplify/amplify-ios/issues/270 
 - Storage: https://github.com/aws-amplify/amplify-ios/issues/339
 - DatasStore/API: https://github.com/aws-amplify/amplify-ios/issues/340
    - Particularly here: https://github.com/aws-amplify/amplify-ios/issues/340#issuecomment-592726629
 - Unsure what you mean by this one, can you clarify?

Apologies you feel like responses are slow, we have a weekly on-call rotation that both addresses issues full time on this repo and the SDK and we try to answer them as quickly as possible as we iterate. Do you have a particular issue that you've posted you can point me to that has not been answered yet? 

We will launch the GA of the Amplify iOS libraries this year. We are shooting for GA around Q2-Q3 timeline, but actively working on it to get there as soon as we complete functionality and are sure it is as stable and bug free as possible. We launched preview so that we can get customers testing/trying out our implementation and gather feedback so that we don't build just what we think but actively participate in the open source community. Also, just to be clear, the existing AWS Mobile SDK for iOS is GA and production ready. However, it is our goal to make the Amplify iOS libraries the go-to entry point for mobile apps (as with JavaScript)...I'd really like to help address your issues and make sure we are at least tracking the appropriate issues (listed above) or make sure we have anything else you are experiencing tracked. So, please let me know if these above are related, or if you are running into anything else. We will definitely update these issues as we publish/update the codebase/pods and please let me know some clarify on the last bullet there.

cc @drochetti for DataStore/Analytics, @lawmicha for Storage

**Comment by drochetti** [comment]
@jeffla @Ricardo1980 @amuresia @jtmorris314 Amplify for iOS just went GA! The [v1.0.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.0) is officially out.

We also have a [new step-by-step tutorial](https://docs.amplify.aws/start/getting-started/native_setup/q/integration/ios) using `Amplify.DataStore`.

Last but not least, we launched a Discord community, feel free to join us there and share more about your use-cases and experience: https://discord.gg/Px5YVfQ
