### ISSUE TITLE
Auth signOut after webUI signIn does not clear browser session

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-ios#484]
**Describe the bug**
Amplify.Auth.signOut() does not clear the SFAuthentication session. This will not allow the user to signIn again with another users. 

**To Reproduce**
1. signIn using `Amplify.Auth.signInWithWebUI`
2. After successful signIn, signout the user by `Amplify.Auth.signOut`
3. Now try to signIn again using `Amplify.Auth.signInWithWebUI`.
4. The user is not presented a signIn screen, Amplify automatically signin the user to the previous users account.

**Expected behavior**
After signOut `Amplify.Auth.signInWithWebUI` should work as a fresh start.

**Comment by sebsto** [comment]
The way I am working around this is by forcing `ASWebAuthenticationSession` to connect to `/logout` on the Cognito endpoint.

```swift
    func experimentalCleanSignOut() {
        print("Signout succeded, clearing cache")

        // see https://stackoverflow.com/questions/47207914/sfauthenticationsession-aswebauthenticationsession-and-logging-out

        // to clear the SFAuthenticationSession cache and cookie, open a browser and visit this URL.
        // alternatively, it can redirect to myapp:// and have the app handle the redirect.  Should be implemented in AWSCognitoAuth.m ?
    
        DispatchQueue.main.async() {

            let signoutURL = URL(string: "https://amplify-lib-ios-demo-amplify.auth.eu-west-1.amazoncognito.com/logout?client_id=6s54gfquatdab7l888m8ka14k0&logout_uri=myapp://" )
            let authSession = ASWebAuthenticationSession(url: signoutURL!, callbackURLScheme: "myapp://") { url, error in
                if let e = error {
                    print("Error when trying to logout on Cognito : \(e)")
                }
            }
            class PCP : NSObject, ASWebAuthenticationPresentationContextProviding {
                func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
                    return UIApplication.shared.windows.first!
                }
            }
            let pcp = PCP()
            authSession.presentationContextProvider = pcp
            authSession.start()
        }
                    
    }
```

**Comment by royjit** [comment]
Changes are merged to master and will be available in the next release.

**Comment by royjit** [comment]
This has been released in version 1.0.2 - https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.2 . Closing this issue.

**Comment by tahoeWolverine** [comment]
I'm using v1.0.4 and seeing the Amplify.Auth.signInWithWebUI(presentationAnchor: UIApplication.shared.windows.first!) blow right by the provider screen and land on my redirect url with grant code; all after calling Amplify.Auth.signOut(options: options, listener:nil).

Any thoughts? Should I be expecting to see the fix automatically or do I need to try an experimentalCleanSignOut as above?

**Comment by ovidiuadorian-yonder** [comment]
Any fix on this?

**Comment by Kv056** [comment]
I am facing the same issue.
has anyone found the solution?

**Comment by sebsto** [comment]
This is fixed since a few months. Test again with Amplify 1.5 
``` 
    // signout
    public func signOut() {

        Amplify.Auth.signOut() { (result) in
            switch result {
            case .success:
                print("Successfully signed out")
            case .failure(let error):
                print("Sign out failed with error \(error)")
            }
        }
    }
```

**Comment by Kv056** [comment]
I am using Amplify 1.5.0, and also used the same code for sign out but it is not worked for me.

I have used this code for sign in with google.
>  Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!) { result in
            switch result {
            case .success:
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }

**Comment by Kv056** [comment]
this issue is closed but i am getting this issue in 1.5.0.
can anyone help?

**Comment by NicoZettler** [comment]
The issue exists to this day. When I sign out of the app and try to sign in again, I am automatically signed in with the Google account that I was signed in with before, with no option to select a different account. It seems like the Amplify.Auth.signOut() method doesn't clear the cache at all. I'm surprised that this thread was opened almost 3 years ago and to this day no fix seems to be available.

**Comment by sebsto** [comment]
Hello, I just tested again with Cognito signin and I confirm the signout process works as expected.
I understand from your message that you are using "Login with Google" and Google store session cookies onthe user your browser that prevents to authenticate as a different user after signout.  
I think this problem is not related to Amplify, but to Login with Google.  
After an application signout, your application should redirect the user to a View or page where he/she has the option to login again, maybe using different "Login with..." providers.

**Comment by Mario8419** [comment]
Same here. When I logout with one user and just sign in with another user (also from another team) and without a browser refresh, previous user data is loaded until a page refresh.

**Comment by tiyberius** [comment]
I am also seeing this behavior and it is unclear from any of the Amplify Docs about how to sign in and out with social auth. Signing in and out using username and password works fine, but social auth is not working and I've been trying to get it work for over a week. I don't see how this is very encouraging for devs, I've thought about switching to Firebase because of this issue alone. This is just _one_ of the troubles I've had with Amplify and while I love AWS and I've been on it forever, this experience has really pushed me to the edge.

**Comment by harsh62** [comment]
> direct the user to a View or page where he/she has the option to login again, maybe using different "Login with..." providers.
@tiyberius I am really sorry that your experience with Amplify Auth has not been great. I would like to resolve that. Can you open an additional issue with all the details, i.e. Amplify Version, your configuration file redacted all the sensitive information, logs with verbose logging enabled, code snippet for recreating the issue, and any other piece of information you think applies to the issue. 

Looking forward to hearing from you.

**Comment by tiyberius** [comment]
@harsh62 thank you for your reply. I was very tired yesterday and not paying very close attention, as I was actually having trouble with the @aws-amplify/amplify-flutter library, not the Swift library. Whoops 😆

Regarding my original issue, I upgraded from amplify_flutter 0.6.0 to amplify flutter 1.0.0 and the problem seems to have gone away.

I am however still struggling with the Amplify CLI and its insistence that all app clients have the identical "Allowed callback URLs" and "Allowed sign-out URLs", as I have a web app and a native app and those two are definitely not the same. I will write this issue up if I can't find a workaround. Cheers!
