### ISSUE TITLE
Confusion with DataStore sync to Cloud

### ISSUE THREAD

**Issue by Nicolaidam** [aws-amplify/amplify-ios#561]
**Describe the bug**
I have problems using DataStore with Userpool Authentication so as a start i try to get DataStore working WITHOUT @auth since this should work. 

I've made a test project with the sample schema from the docs and It works smoothly, Amplify.DataStore.save method actually saves the data successfully into DynamoDB:

enum PostStatus {
  ACTIVE
  INACTIVE
}

type Post @model {
  id: ID!
  title: String!
  rating: Int!
  status: PostStatus!
  comments: [Comment] @connection(name: "PostComments")
}

type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}

However I experience problems syncing DataStore to the cloud when I use my OWN Graphql schema which is a bit more advanced than the sample:

type Caregiver @model {
  id: ID!
  firstName: String!
  lastName: String!
  phoneNumber: String
  street: String
  zip: String
  city: String
  pillrobots: [Pillrobot] @connection(name: "CaregiverRobots")

}

type Pillrobot @model {
  id: ID!
  productionNumber: String!
  firstName: String!
  lastName: String!
  phoneNumber: String!
  street: String!
  zip: String!
  city: String!
  category: String!
  image: String!
  caregiver: Caregiver @connection(name: "CaregiverRobots")
  pills: [Pill] @connection(name: "RobotPills")
}

type Pill @model {
  id: ID!
  barcode: String!
  name: String!
  pillsPerPortion: String!
  reorder: String!
  pillsAdded: String!
  pillsDispensed: String!
  dispenserNumber: String!
  chamber: String!
  pillrobot: Pillrobot @connection(name: "RobotPills")
  doses: [Dose] @connection(name: "PillDoses")
}

type Dose @model {
  id: ID!
  day: String!
  time: String!
  respite: String!
  once: String!
  curfew: String!
  start: String!
  disconnect: String!
  pill: Pill @connection(name: "PillDoses")
}

type ApprovedPills @model {
  barcodeId: ID!
  name: String!
  producerName: String!
  discontinuation: String!
  tabletOrCapsule: String!
  chamber: String!
  diameter: String!
  depth: String!
  weight: String!
  volumePer100Pills: String!
  numberOfPills: String!
  reorder: String!
  createdAt: String!
  updatedAt: String!
}

I have exactly the same setup as the working sample project, the only difference is that I have changed the schema.graphql and generated new models. The new "tabels" get into DynamoDB but for a reason Amplify.DataStore.save doesnt sync to cloud. When i try to save a Caregiver object I get a success message in the terminal but there is nothing in the DynamoDB table. So i guess something is wrong with the API but I dont really understand. Maybe DataStore only support 1 nested element?   

**To Reproduce**
1. Setup sample DataStore project. Test that saving works as it should with sync to cloud
2. Change schema.graphql to my schema
3. You'll not be able to save data in Dynamodb, even though you get success print in terminal

**Expected behavior**
I expect that I can save a Caregiver using my Graphql api.
![appDelegate](https://user-images.githubusercontent.com/32563707/84994509-14ed9700-b14b-11ea-839b-7453e3868feb.png)

**Screenshots**
AppDelegate configuration is attached.

**Environment(please complete the following information):**
I have following pods:
  pod 'Amplify'
  pod 'Amplify/Tools'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'

amplifytools.xcconfig is like this:
push=true
modelgen=true
profile=default
envName=amplify

Amplify version: 4.21.3

**Device Information (please complete the following information):**
iPhone 11

**Comment by Nicolaidam** [comment]
Thank you @lawmicha. 

It almost works as it should now. I think the auto-merge update api did the trick. I have also implemented @auth(rules: [{allow: owner}]) and it works! 

However I have one table ApprovedPills which  should be authenticated by a group "Caregivers" and I cant get through to the data. I've created the "ApprovedPills" manually in DynamoDB so im not sure if im not able to fetch data or if there is a mistake in the created "ApprovedPills" in dynamodb. This is how the graphql is now:

type Caregiver @model @auth(rules: [{allow: owner}]) {
  id: ID!
  firstName: String!
  lastName: String!
  phoneNumber: String
  street: String
  zip: String
  city: String
  pillrobots: [Pillrobot] @connection(name: "CaregiverRobots")

}

type Pillrobot @model @auth(rules: [{allow: owner}]) {
  id: ID!
  productionNumber: String!
  firstName: String!
  lastName: String!
  phoneNumber: String!
  street: String!
  zip: String!
  city: String!
  category: String!
  image: String!
  caregiver: Caregiver @connection(name: "CaregiverRobots")
  pills: [Pill] @connection(name: "RobotPills")
}

type Pill @model @auth(rules: [{allow: owner}]) {
  id: ID!
  barcode: String!
  name: String!
  pillsPerPortion: String!
  reorder: String!
  pillsAdded: String!
  pillsDispensed: String!
  dispenserNumber: String!
  chamber: String!
  pillrobot: Pillrobot @connection(name: "RobotPills")
  doses: [Dose] @connection(name: "PillDoses")
}

type Dose @model @auth(rules: [{allow: owner}]) {
  id: ID!
  day: String!
  time: String!
  respite: String!
  once: String!
  curfew: String!
  start: String!
  disconnect: String!
  pill: Pill @connection(name: "PillDoses")
}

type ApprovedPills @model @auth(rules: [{allow: groups, groups: ["Caregivers"], operations: [read]}]) {
  id: ID!
  name: String!
  producerName: String!
  discontinuation: String!
  tabletOrCapsule: String!
  chamber: String!
  diameter: String!
  depth: String!
  weight: String!
  volumePer100Pills: String!
  numberOfPills: String!
  reorder: String!
}

![image](https://user-images.githubusercontent.com/32563707/85126094-12636e00-b22d-11ea-943c-078963eb8f60.png)

![image](https://user-images.githubusercontent.com/32563707/85126195-43dc3980-b22d-11ea-9804-475d2ca88fb1.png)

![image](https://user-images.githubusercontent.com/32563707/85126267-6e2df700-b22d-11ea-96ed-304d1e5588b0.png)

![image](https://user-images.githubusercontent.com/32563707/85126435-c2d17200-b22d-11ea-84f2-91cfe07e62cc.png)

**Comment by Nicolaidam** [comment]
Do I have to configure an extra authorization type in amplify upadte api maybe?

**Comment by lawmicha** [comment]
Hi @Nicolaidam , sorry for the delay, and thanks for explaining with detailed steps

### Static group authorization
By annotating the type with the `auth` directive, `allow: groups`, and `groups` field. this enables specific users enrolled in `groups` to have restricted access to the data (specified by the `operations`
Take this for example: 
`type ApprovedBlog @model @auth(rules: [{allow: groups, groups: ["ApprovedBloggers"], operations: [read, create]}]) {`
An ApprovedBlog can only be created and read by users enrolled in the `ApprovedBloggers` group

[For more information on static group authorization](https://docs.amplify.aws/cli/graphql-transformer/directives#static-group-authorization)

### AppSync console
1. When `user1` is not in the group, I was not able to create an Approved Blog
```
document:
mutation createApprovedBlog($input:CreateApprovedBlogInput!) {
  createApprovedBlog(input: $input) {
    id
    blogId
    _version
    _deleted
    _lastChangedAt
    createdAt
    updatedAt
  }
}
variables:
{
  "input": {
    "id": "1111"
  }
}
response:
Not Authorized to access createApprovedBlog on type ApprovedBlog
```

2. Created the Group "ApprovedBloggers", added `user2` to the group, and I was able to create data through the AppSync console. (Had to Logout `user2` and back in)

3. Create a subscription with `user1`. User1 is not in the group. this fails with
```
subscription onCreateApprovedBlog {
  	onCreateApprovedBlog {
      id
      blogId
      _version
      _deleted
      _lastChangedAt
      createdAt
      updatedAt
    }
}
response:
Connection failed: {\"errors\":[{\"errorType\":\"Unauthorized\",\"message\":\"Not Authorized to access onCreateApprovedBlog on type Subscription\"}]}
```
4. Create a subscription `user2`. this is successful and data is returned on the subscription when i trigger a successful create mutation from another console while subscribed.

5. Running the app with `user1` signed in. DataStore will start the sync engine and create subscriptions for each model, including the `ApprovedBlog` type. When it fails to create a subscription for the ApprovedBlog type, the entire sync engine fails. This is an issue because not all users will be in the approved group upon sign-up. So first, the sync engine fails when the user is not authorized (this is expected), and second, the sync engine fails even though a signed in user is partially authorized (can create subscriptions for models with `allow: owner` but not for the model with `allow: groups`)

6. Running the app with `user1` signed in. Subscriptions in the SyncEngine were created successfully. the App also listens for changes to the local store using `DataStore.publisher`
```
func approvedBlogSubscription() {
    approvedBlogListener = Amplify.DataStore.publisher(for: ApprovedBlog.self).sink(receiveCompletion: { (completion) in
        switch completion {
        case .failure(let error):
            print("Error \(error)")
        case .finished:
            print("Finished")
        }
    }) { (mutationEvent) in
        DispatchQueue.main.async {
            do {
                self.subscriptionData2 = try mutationEvent.decodeModel(as: ApprovedBlog.self).id
            } catch {
                print("Failed to decode \(mutationEvent)")
            }

        }
    }
}
```

When i trigger a create mutation from the AppSync console, the app was able to get the data on the subscription, reconcile the data back to local store, and the publisher was called with the new data. A running app would see the same data as if I created the a subscription through the AppSync console for that model.

7. Creating data in dynamoDB. When the data is created in DynamoDB, the subscriptions will not be called, I believe the subscriptions are only called when the corresponding mutation is triggered. This is most likely the reason why you do not see data in the App. This is also prone to errors since inserting data into DynamoDB can break the data integrity when bypassing AppSync validation logic. If the data is accruately added, DataStore's sync engine will evetually trigger a sync query based on the sync interval and data that was added to dynamoDB will be added back to the local store.

**Comment by Aken27** [comment]
Hi, I am also facing same issue while using graphql api with amazon cognito as default authentication. It continuously tries to connect to the api but always failing. I have taken care of everything as mentioned by @lawmicha for @auth directive. My ios App is unable to sync the data with the cloud. I have checked the recieptmodel app by @lawmicha and has done everything same like it but still I'm not able fulfill my purpose. I am attaching my schema with it and even though I have signed in still the app is unable to connect with the api.
![Screenshot 2020-07-05 at 3 27 13 AM](https://user-images.githubusercontent.com/59662149/86521523-9180b500-be6f-11ea-8e78-06adf6e91cb6.png)
![Screenshot 2020-07-05 at 3 27 27 AM](https://user-images.githubusercontent.com/59662149/86521527-96456900-be6f-11ea-92c5-88192cd25337.png)


![Screenshot 2020-07-05 at 3 25 39 AM](https://user-images.githubusercontent.com/59662149/86521504-3fd82a80-be6f-11ea-823b-877a823aad3f.png)

**Comment by lawmicha** [comment]
Hi @Aken27 sorry you are seeing this issue, I have opened a new issue to take a look. Please take a look over in https://github.com/aws-amplify/amplify-ios/issues/622

Closing this issue now since the latest question regarding dynamoDB from the original question has been answered
