### ISSUE TITLE
RESTRequest to API Gateway JWT Authorizer bad token

### ISSUE THREAD

**Issue by aguigon** [aws-amplify/amplify-ios#618]
Hello team,

We are currently working with the SDK with:

Cognito User Pool -> for Authentication
API Gateway + JWT Authorizer + Lambda -> for HTTP REST APIs

We have the following amplifyconfiguration.json:

```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "apis": {
          "endpointType": "REST",
          "endpoint": "https://xxxx.xxxxxxxx.com",
          "region": "eu-west-1",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        }
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-west-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
              "Region": "eu-west-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-west-1_xxXXxXXXx",
            "AppClientId": "xxxxxxxxxxxxxxxxx",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```
The configuration itself seems to work. We are able to signUp/signIn users.

The issue is when we want to use:
`Amplify.API.get(RESTRequest)`

API Gateway return a 403 Forbidden error. We did a lot of tests and it appear that the request use the: tokens.idToken as Authorization header but API Gateway authorizer wait for tokens.accessToken.

It works well with the Android SDK & JS SDK with the same configuration, the issue is only with ios-sdk.

Is there an hidden configuration to change this behavior or something else to know ?

Like with the JS SDK:

```
"API": {
        "endpoints": [
          {
              "name": "apis",
              "endpoint": "https://xxxx.xxxxxxxx.com",
              "custom_header": async () => { 
 
                // with Cognito User Pools use this:
                return { 
                  Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}`
                }
              }
          }
        ]
      }
```

Thank you,

**Comment by lawmicha** [comment]
Hi @aguigon, sorry for the inconvenience caused. API requests are intercepted with the idToken from [here](https://github.com/aws-amplify/amplify-ios/blob/eb5b7ff98ae9ac090dc8c71e374b8f3bcb0ee472/AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift#L75) when using the [default cognito interceptor](https://github.com/aws-amplify/amplify-ios/blob/eb5b7ff98ae9ac090dc8c71e374b8f3bcb0ee472/AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/UserPoolRequestInterceptor.swift). if you would like to override this like the JS example you have there, you will have to set `authorizationType` to "OPENID_CONNECT" and implement your own interceptor as described in here: https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios Simply setting the authorization header in the request will have the default interceptor replace the value that you've set. 

Since you have mentioned that JS and Android works for you, this sounds like a bug on iOS and having a custom interceptor should just be a temporary solution. [Android is also using accessToken](https://github.com/aws-amplify/amplify-android/blob/12ec8e9819228f63bd677a0431a5ab191f79d9e1/aws-api/src/main/java/com/amplifyframework/api/aws/sigv4/DefaultCognitoUserPoolsAuthProvider.java#L75)

According to the [AWS docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html), both can be passed to the service.

**Comment by aguigon** [comment]
Hi @lawmicha, 

thank you for your feedback. I try to see if we can implement your temporary solution while we wait for an update regarding this issue.

**Comment by palpatim** [comment]
Released in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.1.0
