### ISSUE TITLE
AWSDynamoDBStoragePlugin not found

### ISSUE THREAD

**Issue by C4RR13P0TT3R** [aws-amplify/amplify-ios#636]
**Describe the bug**
After setting up the API plugin via the CLI, including a CRUD JS Lambda and a respective DynamoDB, adding the API Plugin into the iOS Project via Cocoapods and adding the API plugin in the AppDelegate I get the following error on App launch:

Failed to initialize Amplify with StorageError: No plugin has been added for 'awsDynamoDbStoragePlugin'.
Recovery suggestion: Either add a plugin for 'awsDynamoDbStoragePlugin', or use one of the known keys:

I cannot find a respective resource within the docs (https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios)
Furthermore from guessing a respective Pod I didn't succeed as well

**Comment by mTRx0** [comment]
Are you trying to set up `storage` or `api`?

**Comment by C4RR13P0TT3R** [comment]
I am trying to set up an API service. And as part of the setup process within the CLI, I create an API related Lambda performing the CRUD logic on a Dynamo DB, which I do create as well within the Amplify CLI

**Comment by lawmicha** [comment]
Hi @C4RR13P0TT3R, apologise for the confusion, awsDynamoDbStoragePlugin has not been built for iOS even though it was added to the `amplifyconfiguration.json`. If you are setting up an REST API through `amplify add api`, you should be able to use the APIPlugin to make requests to your API Gateway to trigger the lambda that calls into DynamoDB so you shouldn't need to access DynamoDB directly. See https://docs.amplify.aws/lib/restapi/getting-started/q/platform/ios#install-amplify-libraries for more details on making calls to the API gateway.

Although you are getting the failure from StorageError, it should not crash the app. (amplify configuraion should still succeed, previous issue fixed in here https://github.com/aws-amplify/amplify-ios/pull/543). Which Amplify Library version are you using? The latest is 1.0.4

**Comment by C4RR13P0TT3R** [comment]
Hi @lawmicha. Thank you for the fast response. Indeed the app doesn't crash. According to my `amplifyconfiguration.json`im am using version 1.0

**Comment by drochetti** [comment]
Since this has no impact on apps since version `1.0.4`. In the future we will improve the CLI experience so unsupported plugins aren't added to the configuration file, but in the meantime there's no action we can take on Amplify.
