### ISSUE TITLE
Usage question about using Amplify with AWSAppSync

### ISSUE THREAD

**Issue by ekmwilson** [aws-amplify/amplify-ios#716]
My team is using the [AWSAppSync SDK for iOS](https://github.com/awslabs/aws-mobile-appsync-sdk-ios) for making calls to our AppSync APIs. We'd like to eventually shift to the newer Amplify SDK, but our current requirement is to use that one.

We're about to implement Cognito Auth in our app and in an effort to use the recommended Amplify SDK we're attempting to use this SDK for Auth but we're seeing some issues when initializing Amplify. We've followed the docs to initialize Amplify by adding the follow to our AppDelegate's `application:didFinishLaunchingWithOptions` method and expect that it is taking the configuration values from our amplifyconfiguration.json file:
```
  do {
        try Amplify.add(plugin: AWSCognitoAuthPlugin())
        try Amplify.configure()
        print("Amplify configured with auth plugin")
    } catch {
        print("Failed to initialize Amplify with \(error)")
    }

```
Later, we create the AppSync client with the configuration values in awsconfiguration.json:
`let appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)`

When we run our social sign in with web ui I can tell it is taking the Auth properties (like `CognitoUserPool` and `Auth`) from the awsconfiguration.json config and not the amplifyconfiguration.json config. Is this the expected behaviour? Or is there a way to use our awsconfiguration.json file for our AppSync configuration and the amplifyconfiguration.json file for our Cognito Auth configuration?

**Comment by DongQuanRui** [comment]
Hi, @ekmwilson. Thanks for reaching out. 
- First, I don't think it will pick up `awsconfiguration.json` when trying to configure `CognitoAuthPlugin` and you can tell for sure looking into `AmplifyConfigurationInitialization.swift` , `amplifyconfiguration.json` is programmatically picked up. You can also tell `AppSync` is picking up `awsconfiguration.json` if you take a look at `AWSAppSyncClientInfo.swift` Can you please verify that in your code again?
- If you want to making sure to use separate `json` file for different configuration. You can remove the blocks you don't want in two `*configuration.json` files. For example, you want `awsconfiguration.json` for `AppSync`, then you can remove `"CognitoUserPool": {}` and `"Auth": {}` blocks from it. And you want `amplifyconfiguration.json` for `CognitoAuth`, you can remove `"api": {}` block. But this is an unnecessary step in my opinion because of the explanation I made in the first bullet. 

Feel free to reach out again if you have further question.

**Comment by gevartosky** [comment]
Hi @DongQuanRui. I'm working with @ekmwilson on this.

As you mention on bullet 2, I removed the  the blocks `"CognitoUserPool": {}` and `"Auth": {}` from `awsconfiguration.json`, leaving it only with `AppSync`, and I have the `amplifyconfiguration.json` only with `"CognitoUserPool": {}` and `"Auth": {}`. 

What happens is, whoever one gets configured first seems to be dictating the values used from `Amplify` and `AppSync`. 
Calling:
```swift
do {
  try Amplify.add(plugin: AWSCognitoAuthPlugin())
  try Amplify.configure()
  print("Amplify configured with auth plugin")
} catch {
  print("Failed to initialize Amplify with \(error)")
}
```
and then 
```swift
let appSyncServiceConfig = try AWSAppSyncServiceConfig(forKey: configurationKey)
```
Would populate `AWSInfo`(`AWSCognitoAuthPlugin+Configure.swift` line 33) with `amplifyconfiguration.json` which would not have `AppSync` configuration, meaning that on the app I can login using `Amplify.Auth.signInWithWebUI` but I can't make any `AppSync` calls.

Inverting the configuration call order would populate `AWSInfo`(`AWSAppSyncServiceConfig.swift` line 43) with the `awsconfiguration.json`. This time, the app will call `AppSync` services but It crashes on `AWSMobileClient.swift line 417` when calling `Amplify.Auth.signInWithWebUI` because the `awsconfiguration.json` file does not have the `"Auth": {}` information.

I thought about moving `AppSync` configurations from `awsconfiguraiton.json` to `amplifyconfiguration.json` and have everything there but the amplify version decodes the file with a set of specific coding keys, discarding `"AppSync": {}` and everything that does not matches.

Also, `"Auth": {}` is constructed like 
```
"Auth": {
 "Default": {
  "OAuth": {}
 }
}     
```
I'm curious about this "Default" layer between "Auth" and "OAuth", does it mean there is a possibility to have other configuration? like: 
```
"Auth": {
 "Default": {
  "OAuth": { default OAuth configuration }
 },
 "AnotherEnvironment": {
  "OAuth": { another OAuth configuration }
 }
}     
```
