### ISSUE TITLE
Declaration 'resultPublisher' cannot override more than one superclass declaration

### ISSUE THREAD

**Issue by dzhou10** [aws-amplify/amplify-ios#717]
**Describe the bug**
I am following this guide to use amplify ios with appsync, but got this error in the last step.
Declaration 'resultPublisher' cannot override more than one superclass declaration
https://docs.amplify.aws/start/getting-started/setup/q/integration/ios#add-amplify-to-your-application

**To Reproduce**
1. Follow the steps until last step
https://docs.amplify.aws/start/getting-started/setup/q/integration/ios#add-amplify-to-your-application

**Expected behavior**
I shall build successfully, but got above issues.

**Screenshots**
<img width="1133" alt="Screen Shot 2020-08-17 at 10 15 55 AM" src="https://user-images.githubusercontent.com/8179189/90424258-a8bbe080-e072-11ea-8aef-044b95b753f3.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 0.10.0]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 5.0]

**Device Information (please complete the following information):**
 - Xcode: 11.3.1
 - Device: IPhone 7 Plus
 - iOS Version: iOS 13.3.1

**Comment by palpatim** [comment]
@dzhou10 Thanks for reporting. This appears to be related to the new Combine support we introduced in Amplify 1.1.0. However, I don't see this error on Xcode 11.4.1 or greater, only on Xcode 11.3.1. (I don't have 11.4 installed to test it.) It appears that this requires Swift 5.2 or greater to compile.

Can you try building this with Xcode 11.4, or install the Swift 5.2 toolchain and see if that fixes the issue for you?

**Comment by palpatim** [comment]
Yep, this seems like it was fixed in Swift 5.2 along with SR-4206 that fixed some method handling between protocols & classes:

- https://bugs.swift.org/browse/SR-4206
- https://bugs.swift.org/browse/SR-10198
- https://github.com/apple/swift/pull/26536
- https://github.com/apple/swift/blob/master/CHANGELOG.md#swift-52

**Comment by dzhou10** [comment]
Thanks for your help, @palpatim! I will try to upload my xcode from 11.3.1 to latest version to see if the issue is fixed.  Will let you know after I tried out. Thanks!

**Comment by upkesh** [comment]
Hi @dzhou10, Did you get a chance to try this issue with latest version of XCode?

**Comment by palpatim** [comment]
Based on my research and testing, I'm going to optimistically close this issue. If you still see this happen in Xcode 11.4 or greater, please reopen and provide additional details.

**Comment by palpatim** [comment]
For developers who are unable to upgrade to Xcode 11.4, an alternative would be to upgrade your [Swift toolchain](https://swift.org/download/#installation) to 5.2 or higher.

Please note that you must also copy compiler-rt files from Xcode to the toolchain as detailed in https://bugs.swift.org/browse/SR-12001. For example, in my installation, I copied into the Swift 5.2 toolchain with:

```bash
sudo cp $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/*/lib/darwin/libclang_rt.*.a /Library/Developer/Toolchains/swift-5.2-RELEASE.xctoolchain/usr/lib/clang/7.0.0/lib/darwin/
```

Finally, be aware that if you build an app for the AppStore, you must use the version of Swift that comes with the Xcode version you’re building with, so while this will unblock your development, in order to submit to TestFlight or AppStore, you'll have to use Xcode 11.4 or higher.
