### ISSUE TITLE
Question DataStore: How long is websocket connected by default?

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-ios#851]
When we start the app, it connects through websocket to our backend. It receives keepAlive signals in an interval. 
How long is the timeout set by default and can we change this value?
Can't find any information. Looked into the DataStoreConfiguration file, but there isn't any connection handled.
Any information on this topic?

**Comment by wooj2** [comment]
Hi @chris-mds,

Great question you were probably looking in the DataStore documentation, but DataStore uses the Amplify API GraphQL category, which makes use of the AWS AppSync Service -- therefore, to answer your question, we'll need to dive into AppSync.

I believe that connectionTimeout value is what you are referring to.  The client first sends a `connection_int` message to the service, and the service responds back with how long the client must wait before deciding to terminate the websocket connection.  I believe this is a server side configuration parameter which defaults to 5 minutes (300,000 ms).  More information can be found here:
https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html

Currently there I am unaware of any way to configure the timeout, as there seems to be a similar request here:
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/512

Would you be able to tell us about your use case for wanting to update connection timeout value?

**Comment by chris-mds** [comment]
Hi @wooj2 ,

maybe I misunderstood something. The client always stays online, when there is a internet connection?
My use case is that in my app there is a dashboard with realtime data. This dashboard on an iPad is open for minimum 8 hours, so I want to ensure, that there is no auto disconnect after a specific time.

**Comment by wooj2** [comment]
Hi @chris-mds ,

Yes, the websocket connection should stay connected as long as there is a valid internet connection.  Keep-alive messages are sent periodically from the service to the phone, to keep the connection alive.  If your internet connection is severed (your phone goes off wifi, or looses cell reception), we implement an exponential backoff algorithm in attempts to restart the sync engine (this includes doing a full/delta sync, re-establishing websocket/subscriptions, and sending out any mutations that were made while the device was offline).

With regards to a maximum amount of time that you can be connected to the websocket, I am unaware of any maximum.  Also, I am unaware of any code which will automatically disconnects you after a specific time.  If you do run into either of these cases, please let us know, so we can help further debug.

**Comment by chris-mds** [comment]
This is answering my question, thank you

**Comment by mchitson** [comment]
@wooj2 hi if i understand correctly, it is appsync service itself not datastore is the one that will try to re-establish subscriptions, meaning if my phone was temporarily disconnected and someone else had mutated my database, appsync will send me the mutations my subscription missed? i noticed that i get a timeout disconnect even before 5 mins in my appsync subscription. is there a reason for that? can we increase the timeout as well? My app is being used in areas of spotty reception. also what happens when there's a timeout and then internet comes back on, is there a way to force subscriptions again?

**Comment by palpatim** [comment]
@chris-mds , @wooj2 

> With regards to a maximum amount of time that you can be connected to the websocket, I am unaware of any maximum. Also, I am unaware of any code which will automatically disconnects you after a specific time. If you do run into either of these cases, please let us know, so we can help further debug.

The AWS AppSync service [defines a maximum lifespan of 24 hours](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html#keep-alive-message) for any connection. However, as @wooj2 says, we do not have any client code that tracks that--if the service terminates the connection, the library would return that up the chain as a disconnection.

@mchitson 

> hi if i understand correctly, it is appsync service itself not datastore is the one that will try to re-establish subscriptions, meaning if my phone was temporarily disconnected and someone else had mutated my database, appsync will send me the mutations my subscription missed

I'm not sure exactly what you mean. AppSync *does* have message delivery guarantees: if the client doesn't acknowledge receipt of a message, the service will re-attempt message delivery as long as the subscription is connected. However, if the connection is dropped, the client would be responsible for re-establishing a connection.

> i noticed that i get a timeout disconnect even before 5 mins in my appsync subscription. is there a reason for that? can we increase the timeout as well?

The keepalive timeout is set by the service. The client defaults to 5 minutes as it establishes a connection, but will respect whatever value the service returns. (Currently, the service also returns 5 minutes, so it's a reasonable default :) )

As for your report of early termination, it's possible that the spotty network conditions are causing the connection to be dropped. In those cases, DataStore will automatically re-subscribe when it detects the network has resumed. (I'm not sure whether we've tested the case of what happens after the service terminates a connection after the 24-hour limit, since mobile apps aren't usually active in the foreground for that long. :))

Hope this helps. If you have other questions, or believe you're encountering a bug, please open a new bug report with details and we'll investigate further.
