### ISSUE TITLE
AppSyncRealTimeClient Validation error of type MissingFieldArgument: Missing field argument owner @ 'onCreateTodo'

### ISSUE THREAD

**Issue by mschonvogel** [aws-amplify/amplify-ios#854]
I'm trying to add some access control to the todo example. The plan is to limit access to one owner and multiple readers.

**Describe the bug**
When adding the following  auth rule
`{ allow: owner, ownerField: "readers", operations: [read] }`

the websocket seems to be stuck in an infinite loop and responds with the following error message over and over again:
```
2020-10-26 11:01:38.432822+0100 chat[5408:107810] Websocket write - {"id":"4F4F2C65-7591-4961-A195-9795E76643AB","payload":{"data":"{\"query\":\"subscription OnCreateTodo {\\n  onCreateTodo {\\n    id\\n    createdAt\\n    description\\n    name\\n    owner\\n    priority\\n    readers\\n    updatedAt\\n    __typename\\n    _version\\n    _deleted\\n    _lastChangedAt\\n  }\\n}\"}","extensions":{"authorization":{"Authorization":"eyJraWQiOiJMQUxNZktzb2pkQ2x6NDdSamNzSkZ0TnRpbkNnU3FjMlRcL0RhZGFpNEMxWT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3YzZmOTQ5Ny1jN2ZiLTRlOTEtODk4Ni1iNGY4NzQwNzkwNWEiLCJldmVudF9pZCI6IjdjMmIwODk0LTA5YmMtNDNkNS1hMzNhLWRkNmMzODIwYWU1MCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2MDM2NjMxNTAsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbVwvZXUtY2VudHJhbC0xX1E4aldiVDFDVSIsImV4cCI6MTYwMzcxMDA4OCwiaWF0IjoxNjAzNzA2NDg4LCJqdGkiOiJiNmQ5NmUxZC02ZDczLTQ4YTAtYTRlYy03NzcyMzBiMGFjMGYiLCJjbGllbnRfaWQiOiIzZjN2bjZkMnFhcjg1ZXU0NXFybTVuZmkyZSIsInVzZXJuYW1lIjoiN2M2Zjk0OTctYzdmYi00ZTkxLTg5ODYtYjRmODc0MDc5MDVhIn0.xzJJFlGxgk6qZsPmRUc4mh-YilvSMpZLOjFpwm7pyvQaV_cj-b82LgwykGn0dSPSRzijZUMEpW1H4NVZ4G_LPku1CBNwyoDuxuDxugZbUXRniRUp6UcQTm3lcsJ3UO6b1ONvrTA7lm4qXFyJHhSOqkUsBx7AOsUmIVXyA9yiAdboA0Q1bORgj-YxU3MyKSwZFStOtAKVpUdFPN_2-EtkxtXeSgEiCL0YCeJebFZviKBqsws5dUMvV41zSVoEqL8AWexxPdRGMa9KQ-ip1Rw2wvaW7iSPw9lnErZqrrwiqPDM0jyl8EXYFcPX_672O5Ilu8mJo1s_1p6KQnlprocT9w","host":"11342134123412412334.appsync-api.eu-central-1.amazonaws.com"}}},"type":"start"}
2020-10-26 11:01:38.437493+0100 chat[5408:107794] WebsocketDidReceiveMessage - {"id":"5DEB4FC3-20DE-4443-97A2-C806052EF255","type":"error","payload":{"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onCreateTodo'"},{"message":"Validation error of type MissingFieldArgument: Missing field argument readers @ 'onCreateTodo'"}]}}
```

**To Reproduce**
Setup Amplify in AppDelegate:
```
        let models = AmplifyModels()
        let apiPlugin = AWSAPIPlugin(modelRegistration: models)
        let dataStorePlugin = AWSDataStorePlugin(modelRegistration: models)

        let authPlugin = AWSCognitoAuthPlugin()

        do {
            try Amplify.add(plugin: authPlugin)
            try Amplify.add(plugin: apiPlugin)
            try Amplify.add(plugin: dataStorePlugin)
            try Amplify.configure()

            print("Initialized Amplify");
        } catch {
            print("Could not initialize Amplify: \(error)")
        }
```

Use this Schema:
```
enum Priority {
    LOW
    NORMAL
    HIGH
}

type Todo @model
    @auth(rules: [
        { allow: owner },
        { allow: owner, ownerField: "readers", operations: [read] }
    ]) {
    id: ID!
    name: String!
    owner: String
    priority: Priority
    description: String
    readers: [String]
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
}
```

run
```
amplify codegen models && amplify-app
```

**Expected behavior**
Access control that gets respected in subscriptions, queries and mutations.

**Environment(please complete the following information):**
Amplify CLI version: 4.30.0
Installed pods
```
PODS:
  - Amplify (1.4.0):
    - Amplify/Default (= 1.4.0)
  - Amplify/Default (1.4.0)
  - AmplifyPlugins/AWSAPIPlugin (1.4.0):
    - AppSyncRealTimeClient (~> 1.4.0)
    - AWSCore (~> 2.18.0)
    - AWSPluginsCore (= 1.4.0)
    - ReachabilitySwift (~> 5.0.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.4.0):
    - AWSAuthCore (~> 2.18.0)
    - AWSCognitoIdentityProvider (~> 2.18.0)
    - AWSCognitoIdentityProviderASF (~> 2.18.0)
    - AWSCore (~> 2.18.0)
    - AWSMobileClient (~> 2.18.0)
    - AWSPluginsCore (= 1.4.0)
  - AmplifyPlugins/AWSDataStorePlugin (1.4.0):
    - AWSCore (~> 2.18.0)
    - AWSPluginsCore (= 1.4.0)
    - SQLite.swift (~> 0.12.0)
  - AppSyncRealTimeClient (1.4.1):
    - Starscream (~> 3.1.0)
  - AWSAuthCore (2.18.0):
    - AWSCore (= 2.18.0)
  - AWSCognitoIdentityProvider (2.18.0):
    - AWSCognitoIdentityProviderASF (= 2.18.0)
    - AWSCore (= 2.18.0)
  - AWSCognitoIdentityProviderASF (2.18.0)
  - AWSCore (2.18.0)
  - AWSMobileClient (2.18.0):
    - AWSAuthCore (= 2.18.0)
    - AWSCognitoIdentityProvider (= 2.18.0)
    - AWSCognitoIdentityProviderASF (= 2.18.0)
    - AWSCore (= 2.18.0)
  - AWSPluginsCore (1.4.0):
    - Amplify (= 1.4.0)
    - AWSCore (~> 2.18.0)
    - AWSMobileClient (~> 2.18.0)
  - ReachabilitySwift (5.0.0)
  - SnapKit (5.0.1)
  - SQLite.swift (0.12.2):
    - SQLite.swift/standard (= 0.12.2)
  - SQLite.swift/standard (0.12.2)
  - Starscream (3.1.1)
```

**Device Information (please complete the following information):**
Any Device

**Comment by wooj2** [comment]
Hi @mschonvogel ,

Thank you for reaching out to us regarding this issue.

Unfortunately supporting an array of owners with the @auth directive (as you have implemented by setting the ownerField to `Readers`) is not currently supported for subscriptions due to limitations in the AppSync service.  So at this point, this is considered a feature-request as I will be marking this ticket as such.

That being said, we can try to consider some workarounds.  One workaround which may work for you (please let us know), would be to use a group auth rule and static groups setup in Cognito User Pools.

For example:
```
type PostWithReaders
  @model
  @auth(rules: [{ allow: owner },
                { allow: groups, groups: ["Readers"], operations: [read]}
		]) {
    id: ID!
    title: String!
    owner: String
}
```
In terms of expected behavior, if we have two users in the user pool, and one static group called "Readers" with the following assumptions:
a.  `bob` is a user who does not belong to the `Readers` group
b.  `alice` is a user who belongs to the `Readers` group (this is configured in Cognito User Pools)

We should expect the following behavior:
1.  `bob` should be able to query for only posts that have an owner set to `bob`, not `alice`
2.  `alice` should be able to query for posts owned by `alice` or `bob`.  This is because `alice` belongs to the `Readers` group.
3.  `alice` should be able to receive real time updates made by `alice` or `bob`.  This is because `alice` belongs to the `Readers` group.
4.  `bob` should be able to receive real time updates by only "bob", not "alice".  This is because `bob` does not belong to the `Readers` group

Hope this helps.  If not, please let us know more about your use case (and any other constraints) and we can try to brainstorm some other workarounds.

**Comment by mschonvogel** [comment]
Thanks for your detailed answer @wooj2 

My use case is a kind of WhatsApp group chat, so static groups are not really an option for me. 

Can I hook in with a lambda function and somehow control which subscriber gets notified?
Or can I read these static groups dynamically from a field? (And create one group per chatroom?) 

Or is there any other way to implement this?

**Comment by mschonvogel** [comment]
I'm still curious about what's the recommended way to achieve this @wooj2

**Comment by wooj2** [comment]
Hi @mschonvogel 

Sorry for the delay, and thanks for the ping.  I've chatted with a few people on the team and unfortunately this is not something that is easily supported in datastore due to limitations on the AppSync service side.  For the time being, we are considering this as a feature request.

You might be able to accomplish this by using the Amplify API category directly by manually crafting GraphQL subscription documents to get updates on the data you are looking for, but this probably isn't what you're looking for since I would guess that you are interested in the offline capabilities that DataStore provides.

Best of luck!

**Comment by mogalmahesh** [comment]
Hi, This is the same thing I was trying today. 
I see this feature request is closed. 
So does this it is not going to happen or can we expect this to work after a few months? 
If this feature is released, it will be great.

Thanks
