### ISSUE TITLE
Amplify API plugin, or AWSAppSync library?

### ISSUE THREAD

**Issue by ataibarkai** [aws-amplify/amplify-ios#864]
What are the best practices when it comes to using an amplify-generated GraphQL API from an iOS client? Is it best to use the Amplify API plugin or the AWSAppSync library?

There is a lot of langauge out there that says things like 'Amplify Libraries should be used by all new applications'. But [this doc](https://docs.amplify.aws/lib/graphqlapi/concepts/q/platform/ios) suggests that the Amplify API plugin is limited in comparison to the AWSAppSync library.

Is it even possible to get code-gen to work for custom GraphQL queries with the Amplify API-plugin? So far I've only been able to get it working with AWSAppSync.

**Comment by palpatim** [comment]
@ataibarkai 

Your use case will determine the best fit for you. You should treat the Amplify API plugin like an API library for making real-time queries. If you don't need local persistence or offline capabilities, that might be enough for you. DataStore is what we recommend for working with app data since it supports offline, local persistence, and easy-to-understand model-based types. However, Amplify DataStore doesn't support complex objects (that is, a GraphQL model that transparently handles uploading and downloading separate payloads to cloud storage, like a `Profile` model with a `profilePicture` field), so DataStore requires you to handle that use case as two separate operations. Also, DataStore is intentionally opinionated about how it handles modeling data, so custom queries require writing custom GraphQL documents and deserialized types, as opposed to relying on the Amplify code-generated models. The Apollo-based AppSync client has more flexibility in that regard, at the cost of a much more complex type system, and a less robust local local persistence mechanism. 

We do support using Amplify code-generated models for serializing and deserializing to the Amplify API category (e.g., see the first example on https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios which uses a code-generated `Todo` model) , but you won't get automatic persistence, offline capabilities, or sync with your cloud backend. For that, use DataStore.

**Comment by ataibarkai** [comment]
Thank you for the reply here Tim.

Let me copy/paste the remainder of the conversation we had on Discord below here for the benefit of whoever comes across this in the future:

Question:
> As for the Amplify API code generation: I've been able to get model code-gen working, but does the Amplify API also support code-gen for custom GraphQL queries defined in a .graphql file?

Answer:
> Yes if you would like a custom GraphQL request, you will have to hand roll the GraphQL document and variables. Since the AppSync operations do not change drastically across different usages of the directives (https://docs.amplify.aws/cli/graphql-transformer/directives), there are many use cases where the response type can be reused from the model generated classes (amplify codegen models) that already conform to Model. 
> 
> you can see some of the custom graphQL request documentation here: https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios feel free to let us know if there's a use case that you're having troubles with and we can help out

**Comment by palpatim** [comment]
@ataibarkai 

Thanks for archiving @lawmicha's Discord reply on this issue!

Closing for now.
