### ISSUE TITLE
App crashes when building for iOS 12

### ISSUE THREAD

**Issue by gevartosky** [aws-amplify/amplify-ios#878]
**Describe the bug**
After updating the framework to `1.4.1` the app crashes on the launch phase with this error.

**dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /Users/……../……/Amplify.framework/Amplify
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/SwiftUI.framework/SwiftUI: mach-o, but not built for iOS simulator**

**To Reproduce**
1. Build the app on an iOS 12 simulator.

**Environment:**
 - Amplify Framework Version: 1.4.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1.3]

**Device Information:**
 - Device: iPhone X simulator
 - iOS Version: 12.4

**Additional context**
I tried to add `-weak_framework SwiftUI` to `Other Linker Flags` but it still crashes. Also tried on Amplify `1.4.0`

**Comment by palpatim** [comment]
Hi @gevartosky, Amplify requires Swift 5.2 to build, which is available on Xcode 11.4 or later. Hope this helps.

**Comment by gevartosky** [comment]
Thanks @palpatim. I tried with Swift 5.2.4 / Xcode 11.5 but I still get the crash with the same error. Oddly enough the crash does not seem to happen on Xcode 12 with Xcode 11.5 command line tools.

**Comment by palpatim** [comment]
Hmm. I wonder if the new DevMenu is causing issues with your project, as that is the only component that has references to SwiftUI? Investigating.

**Comment by palpatim** [comment]
I can replicate this on Xcode 11.7 against an iOS 12.4 simulator.

We can fix this by specifying a `weak_frameworks` configuration option.

But I'm not clear why we have to do this. The DataStore module uses `Combine`, which was also introduced in iOS 13. My best guess at this point is that there is a bug in earlier versions of Xcode that somehow subverts or bypasses the automatic [weak linking of system frameworks](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html) that Xcode offers by default. That is supported by [this Reddit thread](https://www.reddit.com/r/swift/comments/c5wq4o/integrating_swiftui_into_project_with_minimum_ios/), wherein a user states:

> The problem is that Xcode is injecting some extra code (just for previews) into the app which is not marked with @available attribute. This is what causes the build failure.

Assuming that's correct, it would appear that this was fixed in Xcode 12, which is why you didn't see the issue when you upgraded. Since Amplify does support back to Xcode 11.4, we'll add the explicit `weak_frameworks` config to our podspec, which should fix the issue going forward.

**Comment by palpatim** [comment]
(Technically this was because of the DevMenu, but it wasn't really the DevMenu's fault, so I'm removing the `dev tools` label

**Comment by gevartosky** [comment]
I had the same impression regarding DevMenu. And yes, the `weak_frameworks` thing seems to be an Xcode bug, from what I have been reading.

Thank you @palpatim 🙏

**Comment by lawmicha** [comment]
This has been released in 1.4.4, let us know if you are still seeing the issue
