### ISSUE TITLE
Amplify.Auth.signInWithWebUI immediately loads redirect URL

### ISSUE THREAD

**Issue by blau2** [aws-amplify/amplify-ios#999]
**Describe the bug**
I am using the Amplify SDK with a manually configured `amplifyconfiguration.json` file, as our AWS resources are being provisioned via Terraform by a separate team. Calling `Amplify.Auth.signInWithWebUI` doesn't show the login screen, but rather immediately loads our sign-in redirect page.  My configuration is as follows:

```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "***",
                        "AppClientId": "***",
                        "Region": "***"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "***",
                            "AppClientId": "***",
                            "SignInRedirectURI": "https://***/",
                            "SignOutRedirectURI": "https://***/",
                            "Scopes": ["email", "openid"]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}

```

Our user pool is configured with Apple/Google social sign-in as well as SAML-federated IdPs. I've been able to get the entire authentication flow working -- including the callback to the app via Universal Link, by just manually constructing the login URL and presenting it in a `SafariViewController` --  so I don't think it's an issue with the way our user pool is configured. As this is proving to be quite frustrating, I may choose to just continue with this approach instead of `signInWithWebUI`, but would I still be able to leverage Amplify to handle session management/token refresh?

On a related note: I'm finding the documentation extremely lacking in general for using Amplify with pre-existing AWS resources. I understand the primary use case is to allow mobile app developers to easily spin up backend resources without needing any ops experience, but we don't fall under this category. Is Amplify still the recommended approach given our circumstances, or should we revert back to using the `AWSMobile` SDK (which, as I understand, is being deprecated in favour of Amplify)?

**To Reproduce**
1. Execute the following:
```
Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)
            .resultPublisher
            .sink {
                if case let .failure(authError) = $0 {
                    print("Sign in failed \(authError)")
                }
            }
            receiveValue: { _ in
                print("Sign in succeeded")
            }
            .store(in: &bindings)
```
2. Web view is presented modally with the sign-in redirect page loaded. The login page is never displayed and the callback does not occur.
![Screen Shot 2020-12-30 at 4 33 27 PM](https://user-images.githubusercontent.com/1384321/103388294-2120bc80-4abd-11eb-8e23-12e6f7e7c203.png)

**Expected behavior**
The login web UI is displayed:

![Screen Shot 2020-12-30 at 4 34 49 PM](https://user-images.githubusercontent.com/1384321/103388287-1403cd80-4abd-11eb-854f-fdea1a0684bd.png)

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.2
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 11 Simulator
 - iOS Version: 14.3
 - Specific to simulators: No

**Additional context**

**Comment by palpatim** [comment]
Hi @blau2,

Using Amplify with existing resources is supported. There's no specific requirement that you use the CLI to provision your backend resources or generate your configuration files, as long as the end configuration meets the requirements of what *would* have been generated using the CLI. The complication is that the CLI sets up a lot of resources and configurations, and encodes recommended best practices into those setups. Maintaining accurate documentation on each of those in their various permutations would be challenging, as I'm sure you can imagine.

My best advice would be to use the Amplify CLI to set up a set of test resources that mimics your setup, and then to compare the resources to ensure that the ones set up in your other workflow includes all the relevant info. In particular, I'd recommend paying special attention to the user pool configuration, Hosted UI setup, associated IAM policies, and the callback URL generated by Amplify, to make sure that your configs are wired up correctly.

I wouldn't recommend reverting to the AWS Mobile SDK since the HostedUI use case you describe is supported in Amplify.

**Comment by blau2** [comment]
Hi @palpatim, thanks for the quick response. I've taken your advice and used the Amplify CLI to generate a config file with test resources and have adapted it to our project.
